RUNTIME_DATA_FILE_BEGIN(achievement.enc)

RUNTIME_DATA_TYPE_BEGIN(AchievementCondition, "cabal_achievement.achievement.condition.condition_info")
	RUNTIME_DATA_PROPERTY(Int32, AchievementID, "achv_id")
	RUNTIME_DATA_PROPERTY(Int32, PreviousID, "pre")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(AchievementConditionDetail, "condition_detail")
		RUNTIME_DATA_PROPERTY(Int32, Step, "step")
		RUNTIME_DATA_PROPERTY(Int32, WhoID, "who_id")
		RUNTIME_DATA_PROPERTY(Int32, ActionID, "action_id")
		RUNTIME_DATA_PROPERTY(Int32, TargetID, "target_id")
		RUNTIME_DATA_PROPERTY(Int32, SituationID, "situation_id")
		RUNTIME_DATA_PROPERTY(Int32, Group, "group")
	RUNTIME_DATA_TYPE_END_CHILD(AchievementConditionDetail)
RUNTIME_DATA_TYPE_END(AchievementCondition)

RUNTIME_DATA_TYPE_BEGIN(AchievementWho, "cabal_achievement.achievement.who.who_info")
	RUNTIME_DATA_PROPERTY(Int32, WhoID, "who_id")
	RUNTIME_DATA_PROPERTY(Int32, Type, "type")
	RUNTIME_DATA_PROPERTY(Int32, Value, "value")
	RUNTIME_DATA_PROPERTY(Int32, MessageID, "msg_id")
RUNTIME_DATA_TYPE_END(AchievementWho)

RUNTIME_DATA_TYPE_BEGIN(AchievementAction, "cabal_achievement.achievement.action.action_info")
	RUNTIME_DATA_PROPERTY(Int32, ActionID, "action_id")
	RUNTIME_DATA_PROPERTY(Int32, Type, "type")
	RUNTIME_DATA_PROPERTY(Int32, Value, "value")
	RUNTIME_DATA_PROPERTY(Int32, MessageID, "msg_id")
RUNTIME_DATA_TYPE_END(AchievementAction)

RUNTIME_DATA_TYPE_BEGIN(AchievementTarget, "cabal_achievement.achievement.target.target_info")
	RUNTIME_DATA_PROPERTY(Int32, TargetID, "target_id")
	RUNTIME_DATA_PROPERTY(Int32, Type, "type")
	RUNTIME_DATA_PROPERTY(Int32, SubType, "subtype")
	RUNTIME_DATA_PROPERTY(Int32, Value1, "value1")
	RUNTIME_DATA_PROPERTY(Int32, Value2, "value2")
	RUNTIME_DATA_PROPERTY(Int32, MessageID, "msg_id")
RUNTIME_DATA_TYPE_END(AchievementTarget)

RUNTIME_DATA_TYPE_BEGIN(AchievementSituation, "cabal_achievement.achievement.situation.situation_info")
	RUNTIME_DATA_PROPERTY(Int32, SituationID, "situation_id")
	RUNTIME_DATA_PROPERTY(Int32, Type, "type")
	RUNTIME_DATA_PROPERTY(Int32, SubType, "subtype")
	RUNTIME_DATA_PROPERTY(Int32, Value, "value")
	RUNTIME_DATA_PROPERTY(Int32, MessageID, "msg_id")
RUNTIME_DATA_TYPE_END(AchievementSituation)

RUNTIME_DATA_TYPE_BEGIN(AchievementReward, "cabal_achievement.achievement.reward.reward_info")
	RUNTIME_DATA_PROPERTY(Int32, AchievementID, "achv_id")
	RUNTIME_DATA_PROPERTY(Int32, Excess, "excess")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(AchievementRewardDetail, "reward_detail")
		RUNTIME_DATA_PROPERTY(Int32, Step, "step")
		RUNTIME_DATA_PROPERTY(Int32, End, "end")
		RUNTIME_DATA_PROPERTY(Int32, Repeatable, "repeatable")
		RUNTIME_DATA_PROPERTY(Int32, Count, "count")
		RUNTIME_DATA_PROPERTY(Int32, Type, "type")
		RUNTIME_DATA_PROPERTY(Int32, Value, "value")
	RUNTIME_DATA_TYPE_END_CHILD(AchievementRewardDetail)
RUNTIME_DATA_TYPE_END(AchievementReward)

RUNTIME_DATA_TYPE_BEGIN(AchievementSort, "cabal_achievement.achievement.sort.achv_sort")
	RUNTIME_DATA_PROPERTY(Int32, AchievementID, "achv_id")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, Order, "order")
RUNTIME_DATA_TYPE_END(AchievementSort)

RUNTIME_DATA_TYPE_BEGIN(Title, "cabal_achievement.title.title_option.title_info")
	RUNTIME_DATA_PROPERTY(Int32, TitleID, "title_id")
	RUNTIME_DATA_PROPERTY(Int32, Nation, "nation")
	RUNTIME_DATA_PROPERTY(Int32, DisplayType, "display_type")
	RUNTIME_DATA_PROPERTY(Int32, Duration, "duration")
	RUNTIME_DATA_PROPERTY(Int32, AchievementID, "achv_id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(TitleDetail, "title_detail")
		RUNTIME_DATA_PROPERTY(Int32, ForceID, "bforce_id")
		RUNTIME_DATA_PROPERTY(Int32, ValueType, "value_type")
		RUNTIME_DATA_PROPERTY(Int32, ForceValue, "bforce_value")
	RUNTIME_DATA_TYPE_END_CHILD(TitleDetail)
RUNTIME_DATA_TYPE_END(Title)

RUNTIME_DATA_TYPE_BEGIN(TitleSort, "cabal_achievement.title.sort.title_sort")
	RUNTIME_DATA_PROPERTY(Int32, TitleID, "title_id")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, SlotType, "slot_type")
	RUNTIME_DATA_PROPERTY(Int32, Order, "order")
RUNTIME_DATA_TYPE_END(TitleSort)

RUNTIME_DATA_FILE_END