RUNTIME_DATA_FILE_BEGIN(assistant.enc)

RUNTIME_DATA_TYPE_BEGIN(Assistant, "assistant.main.assistant_main")
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_PROPERTY(Int32, CardItem, "card_item")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, Group, "group")
	RUNTIME_DATA_PROPERTY(Int32, Level, "level")
	RUNTIME_DATA_PROPERTY(Int32, Duration, "duration")
	RUNTIME_DATA_PROPERTY(Int32, RequestLevel, "req_lv")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(AssistantAbility, "ability")
		RUNTIME_DATA_PROPERTY(Int32, AttackUse, "attack_use")
		RUNTIME_DATA_PROPERTY(Int32, PassiveSingle, "passive_single")
		RUNTIME_DATA_PROPERTY(Int32, PassiveParty, "passive_party")
		RUNTIME_DATA_PROPERTY(Int32, TriggerSingle, "trigger_single")
		RUNTIME_DATA_PROPERTY(Int32, ActiveParty, "active_party")
	RUNTIME_DATA_TYPE_END_CHILD(AssistantAbility)
RUNTIME_DATA_TYPE_END(Assistant)

RUNTIME_DATA_TYPE_BEGIN(AssistantAttribute, "assistant.attribute.assistant_attribute")
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_PROPERTY(Int32, MovementSpeed, "move_speed")
	RUNTIME_DATA_PROPERTY(Int32, AnimationSpeed, "ani_speed")
	RUNTIME_DATA_PROPERTY(Int32, SocialID, "social_id")
RUNTIME_DATA_TYPE_END(AssistantAttribute)

RUNTIME_DATA_TYPE_BEGIN(AssistantAttack, "assistant.attack.assistant_attack")
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_PROPERTY(Int32, BaseValue, "base_value")
	RUNTIME_DATA_PROPERTY(Int32, AttackRate, "ar")
	RUNTIME_DATA_PROPERTY(Int32, CriticalRate, "critical_rate")
	RUNTIME_DATA_PROPERTY(Int32, CriticalDamage, "critical_damage")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(AssistantAttackAttribute, "attack_attribute")
		RUNTIME_DATA_PROPERTY(Int32, AttackReach1, "attack1_reach")
		RUNTIME_DATA_PROPERTY(Int32, AttackRange1, "attack1_range")
		RUNTIME_DATA_PROPERTY(Int32, AttackType1, "attack1_type")
		RUNTIME_DATA_PROPERTY(Int32, AttackDelay1, "attack1_delay")
		RUNTIME_DATA_PROPERTY(Int32, AttackReach2, "attack2_reach")
		RUNTIME_DATA_PROPERTY(Int32, AttackRange2, "attack2_range")
		RUNTIME_DATA_PROPERTY(Int32, AttackType2, "attack2_type")
		RUNTIME_DATA_PROPERTY(Int32, AttackDelay2, "attack2_delay")
	RUNTIME_DATA_TYPE_END_CHILD(AssistantAttackAttribute)
RUNTIME_DATA_TYPE_END(AssistantAttack)

RUNTIME_DATA_TYPE_BEGIN(AssistantBuff, "assistant.buff.assistant_buff")
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_PROPERTY(Int32, BuffGroup, "buff_group")
	RUNTIME_DATA_PROPERTY(Int32, SkillLevel, "skill_lv")
	RUNTIME_DATA_PROPERTY(Int32, SkillType, "skill_type")
	RUNTIME_DATA_PROPERTY(Int32, TriggerValue, "trigger_value")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(AssistantBuffSkillValue, "skill_value")
		RUNTIME_DATA_PROPERTY(Int32, Order, "order")
		RUNTIME_DATA_PROPERTY(Int32, ForceCodeID, "forcecode_id")
		RUNTIME_DATA_PROPERTY(Int32, Value, "value")
		RUNTIME_DATA_PROPERTY(Int32, LimitValue, "limit_value")
		RUNTIME_DATA_PROPERTY(Int32, DurationTime, "duration_time")
		RUNTIME_DATA_PROPERTY(Int32, ColldownTime, "cool_time")
	RUNTIME_DATA_TYPE_END_CHILD(AssistantBuffSkillValue)
RUNTIME_DATA_TYPE_END(AssistantBuff)

RUNTIME_DATA_TYPE_BEGIN(AssistantItem, "assistant.item.assistant_lv")
	RUNTIME_DATA_PROPERTY(Int32, Level, "lv")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(AssistantItemIndex, "item_index")
		RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_TYPE_END_CHILD(AssistantItemIndex)
RUNTIME_DATA_TYPE_END(AssistantItem)

RUNTIME_DATA_FILE_END