RUNTIME_DATA_FILE_BEGIN(Awaken_auramode.enc)

RUNTIME_DATA_TYPE_BEGIN(AwakenAuraMode, "main.auramode_main")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, TargetSkillIndex, "targetskill_index")
	RUNTIME_DATA_PROPERTY(Int32, SlotCount, "slot_count")
	RUNTIME_DATA_PROPERTY(Int32, MaxGrade, "max_grade")
RUNTIME_DATA_TYPE_END(AwakenAuraMode)

RUNTIME_DATA_TYPE_BEGIN(AwakenAuraPoint, "main.point_main.point")
	RUNTIME_DATA_PROPERTY(Int32, MinTime, "min_time")
	RUNTIME_DATA_PROPERTY(Int32, MaxTime, "max_time")
	RUNTIME_DATA_PROPERTY(Int32, RewardPoint, "reward_point")
RUNTIME_DATA_TYPE_END(AwakenAuraPoint)

RUNTIME_DATA_TYPE_BEGIN(AwakenAuraSlot, "main.point_main.slot_main.slot")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "slot_index")
	RUNTIME_DATA_PROPERTY(Int32, SlotPosition, "slot_position")
	RUNTIME_DATA_PROPERTY(Int32, ForceID, "forceid")
RUNTIME_DATA_TYPE_END(AwakenAuraSlot)

RUNTIME_DATA_TYPE_BEGIN(AwakenAuraSlotOpenCondition, "main.point_main.slot_main.slot_opencondition.slot")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "slot_index")
	RUNTIME_DATA_PROPERTY(Int32, MaxLevel, "max_level")
	RUNTIME_DATA_PROPERTY(Int32, OpenConditionSlot, "open_condition_slot")
	RUNTIME_DATA_PROPERTY(Int32, OpenConditionLevel, "open_condition_level")
	RUNTIME_DATA_PROPERTY(Int32, NameColor, "name_color")
RUNTIME_DATA_TYPE_END(AwakenAuraSlotOpenCondition)

RUNTIME_DATA_TYPE_BEGIN(AwakenAuraSlotOpenConditionMaterial, "main.point_main.slot_main.slot_opencondition.open_material.material")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "slot_index")
	RUNTIME_DATA_PROPERTY(Int32, Order, "order")
	RUNTIME_DATA_PROPERTY(UInt32, MaterialIndex, "material_lndex")
	RUNTIME_DATA_PROPERTY(Int32, NeedCount, "need_count")
RUNTIME_DATA_TYPE_END(AwakenAuraSlotOpenConditionMaterial)

RUNTIME_DATA_TYPE_BEGIN(AwakenAuraSlotOption, "main.point_main.slot_main.slot_opencondition.open_material.option_value.option")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "slot_index")
	RUNTIME_DATA_PROPERTY(Int32, Level, "level")
	RUNTIME_DATA_PROPERTY(UInt32, NeedPoint, "need_point")
	RUNTIME_DATA_PROPERTY(Int32, ForceID, "forceid")
	RUNTIME_DATA_PROPERTY(Int32, Value, "Value")
	RUNTIME_DATA_PROPERTY(Int32, ValueType, "Value_type")
RUNTIME_DATA_TYPE_END(AwakenAuraSlotOption)

RUNTIME_DATA_TYPE_BEGIN(AwakenAuraBonusCondition, "main.point_main.slot_main.slot_opencondition.open_material.option_value.bonus_condition.bonus")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, ConditionIndex, "condition_index")
	RUNTIME_DATA_PROPERTY(Int32, ConditionLevel, "condition_level")
RUNTIME_DATA_TYPE_END(AwakenAuraBonusCondition)

RUNTIME_DATA_TYPE_BEGIN(AwakenAuraBonusValue, "main.point_main.slot_main.slot_opencondition.open_material.option_value.bonus_condition.bonus_value.bonus")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "slot_index")
	RUNTIME_DATA_PROPERTY(Int32, ForceID, "forceid")
	RUNTIME_DATA_PROPERTY(Int32, Value, "Value")
	RUNTIME_DATA_PROPERTY(Int32, ValueType, "Value_type")
RUNTIME_DATA_TYPE_END(AwakenAuraBonusValue)

RUNTIME_DATA_FILE_END