#pragma once

#include <CoreLib/CoreLib.h>
#include <math.h>

#ifndef RUNTIME_DATA_DUMMY_SKILL_CASE
#define RUNTIME_DATA_DUMMY_SKILL_CASE

enum {
	RUNTIME_DATA_DUMMY_SKILL_CASE_BATTLE_MODE_ENCHANT,
	RUNTIME_DATA_DUMMY_SKILL_CASE_BATTLE_MODE_UNKNOWN,
	RUNTIME_DATA_DUMMY_SKILL_CASE_COMBO_MODE,
};

#endif
