RUNTIME_DATA_FILE_BEGIN(BossArena.enc)

RUNTIME_DATA_TYPE_BEGIN(BossArenaSeason, "BossArena.Season")
	RUNTIME_DATA_PROPERTY(Int32, Season, "Season")
	RUNTIME_DATA_PROPERTY(Int32, DungeonIndex, "DungeonIdx")
RUNTIME_DATA_TYPE_END(BossArenaSeason)
RUNTIME_DATA_TYPE_INDEX_SINGLE(BossArenaSeason)

RUNTIME_DATA_TYPE_BEGIN(BossArenaBattleStyle, "BossArena.BsValue")
	RUNTIME_DATA_PROPERTY(Int32, Season, "Season")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(BossArenaBattleStyleValue, "Value")
		RUNTIME_DATA_PROPERTY(Int32, BattleStyleIndex, "BsType")
		RUNTIME_DATA_PROPERTY(Int32, WeightedValue, "WeightedValue")
	RUNTIME_DATA_TYPE_END_CHILD(BossArenaBattleStyleValue)
RUNTIME_DATA_TYPE_END(BossArenaBattleStyle)
RUNTIME_DATA_TYPE_INDEX(BossArenaBattleStyle, Int32, Season)
RUNTIME_DATA_TYPE_INDEX_CHILD(BossArenaBattleStyle, BossArenaBattleStyleValue, Int32, BattleStyleIndex)

RUNTIME_DATA_TYPE_BEGIN(BossArenaScore, "BossArena.ScoreValue")
	RUNTIME_DATA_PROPERTY(Int32, Season, "Season")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(BossArenaScoreValue, "Value")
		RUNTIME_DATA_PROPERTY(Int32, HitScore, "HitScore")
		RUNTIME_DATA_PROPERTY(Int32, CriticalScore, "CriticalScore")
		RUNTIME_DATA_PROPERTY(Int32, ScoreModifyValue, "ScoreModifyValue")
		RUNTIME_DATA_PROPERTY(Int32, MinScore, "minScore")
	RUNTIME_DATA_TYPE_END_CHILD(BossArenaScoreValue)
RUNTIME_DATA_TYPE_END(BossArenaScore)
RUNTIME_DATA_TYPE_INDEX(BossArenaScore, Int32, Season)

RUNTIME_DATA_TYPE_BEGIN(BossArenaRankingPenalty, "BossArena.RankingPenalty")
	RUNTIME_DATA_PROPERTY(Int32, Season, "Season")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(BossArenaRankingPenaltyValue, "Value")
		RUNTIME_DATA_PROPERTY(Int32, Ranking, "Ranking")
		RUNTIME_DATA_PROPERTY(Int32, Before3Week, "Before3Week")
		RUNTIME_DATA_PROPERTY(Int32, Before2Week, "Before2Week")
		RUNTIME_DATA_PROPERTY(Int32, Before1Week, "Before1Week")
	RUNTIME_DATA_TYPE_END_CHILD(BossArenaRankingPenaltyValue)
RUNTIME_DATA_TYPE_END(BossArenaRankingPenalty)
RUNTIME_DATA_TYPE_INDEX(BossArenaRankingPenalty, Int32, Season)
RUNTIME_DATA_TYPE_INDEX_CHILD(BossArenaRankingPenalty, BossArenaRankingPenaltyValue, Int32, Ranking)

RUNTIME_DATA_TYPE_BEGIN(BossArenaRankingReward, "BossArena.RankingReward")
	RUNTIME_DATA_PROPERTY(Int32, Season, "Season")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(BossArenaRankingRewardValue, "Value")
		RUNTIME_DATA_PROPERTY(UInt32, Ranking, "Ranking")
		RUNTIME_DATA_PROPERTY(UInt32, ItemKind, "ItemKind")
		RUNTIME_DATA_PROPERTY(UInt32, ItemOptions, "ItemOpt")
		RUNTIME_DATA_PROPERTY(Int32, DurationIndex, "DurationIdx")
	RUNTIME_DATA_TYPE_END_CHILD(BossArenaRankingRewardValue)
RUNTIME_DATA_TYPE_END(BossArenaRankingReward)
RUNTIME_DATA_TYPE_INDEX(BossArenaRankingReward, Int32, Season)
RUNTIME_DATA_TYPE_INDEX_CHILD(BossArenaRankingReward, BossArenaRankingRewardValue, Int32, Ranking)

RUNTIME_DATA_TYPE_BEGIN(BossArenaSeasonReward, "BossArena.SeasonReward")
	RUNTIME_DATA_PROPERTY(Int32, Season, "Season")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(BossArenaSeasonRewardValue, "Value")
		RUNTIME_DATA_PROPERTY(UInt32, Ranking, "Ranking")
		RUNTIME_DATA_PROPERTY(UInt32, ItemKind, "ItemKind")
		RUNTIME_DATA_PROPERTY(UInt32, ItemOptions, "ItemOpt")
		RUNTIME_DATA_PROPERTY(Int32, DurationIndex, "DurationIdx")
	RUNTIME_DATA_TYPE_END_CHILD(BossArenaSeasonRewardValue)
RUNTIME_DATA_TYPE_END(BossArenaSeasonReward)
RUNTIME_DATA_TYPE_INDEX(BossArenaSeasonReward, Int32, Season)
RUNTIME_DATA_TYPE_INDEX_CHILD(BossArenaSeasonReward, BossArenaSeasonRewardValue, Int32, Ranking)

RUNTIME_DATA_TYPE_BEGIN(BossArenaDailyEntryCount, "BossArena.DailyEntryCount")
	RUNTIME_DATA_PROPERTY(Int32, Count, "Count")
RUNTIME_DATA_TYPE_END(BossArenaDailyEntryCount)
RUNTIME_DATA_TYPE_INDEX_SINGLE(BossArenaDailyEntryCount)

RUNTIME_DATA_TYPE_BEGIN(BossArenaRandomBuff, "BossArena.RandomBuff")
	RUNTIME_DATA_PROPERTY(Int32, Season, "Season")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(BossArenaRandomBuffValue, "Value")
	RUNTIME_DATA_PROPERTY(UInt32, SkillIndex, "skillIdx")
	RUNTIME_DATA_PROPERTY(UInt32, Level, "level")
	RUNTIME_DATA_TYPE_END_CHILD(BossArenaRandomBuffValue)
RUNTIME_DATA_TYPE_END(BossArenaRandomBuff)
RUNTIME_DATA_TYPE_INDEX(BossArenaRandomBuff, Int32, Season)

RUNTIME_DATA_FILE_END