RUNTIME_DATA_FILE_BEGIN(DIR_PATH(Character, Character.xml))

RUNTIME_DATA_TYPE_BEGIN(CharacterTemplate, "Character.BattleStyle")
	RUNTIME_DATA_PROPERTY(Int32, BattleStyle, "Index")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(CharacterTemplateSkillSlot, "SkillSlot")
		RUNTIME_DATA_PROPERTY(Int32, SkillIndex, "SkillIndex")
		RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "SlotIndex")
		RUNTIME_DATA_PROPERTY(Int32, Level, "Level")
	RUNTIME_DATA_TYPE_END_CHILD(CharacterTemplateSkillSlot)
	RUNTIME_DATA_TYPE_BEGIN_CHILD(CharacterTemplateQuickSlot, "QuickSlot")
		RUNTIME_DATA_PROPERTY(Int32, SkillIndex, "SkillIndex")
		RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "SlotIndex")
	RUNTIME_DATA_TYPE_END_CHILD(CharacterTemplateQuickSlot)
	RUNTIME_DATA_TYPE_BEGIN_CHILD(CharacterTemplateInventorySlot, "InventorySlot")
		RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "SlotIndex")
		RUNTIME_DATA_PROPERTY(UInt64, ItemID, "ItemID")
		RUNTIME_DATA_PROPERTY(UInt64, ItemOption, "ItemOption")
	RUNTIME_DATA_TYPE_END_CHILD(CharacterTemplateInventorySlot)
RUNTIME_DATA_TYPE_END(CharacterTemplate)
RUNTIME_DATA_TYPE_INDEX(CharacterTemplate, Int32, BattleStyle)

RUNTIME_DATA_FILE_END