RUNTIME_DATA_FILE_BEGIN(Event.xml)

RUNTIME_DATA_TYPE_BEGIN(Event, "events.event", 64)
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_PROPERTY(Int32, Type, "type")
	RUNTIME_DATA_PROPERTY(Int32, UseFlags, "use_flags")
	RUNTIME_DATA_PROPERTY(Int32, WorldIndex, "world_id")
	RUNTIME_DATA_PROPERTY(Int32, NpcIndex, "npc_id")
	RUNTIME_DATA_PROPERTY_ARRAY(Char, Description, "description", 260, '\0')

	RUNTIME_DATA_TYPE_BEGIN_CHILD(EventDescription, "event_description", 8)
		RUNTIME_DATA_PROPERTY_ARRAY(Char, Description, "content", 260, '\0')
	RUNTIME_DATA_TYPE_END_CHILD(EventDescription, 8)

	RUNTIME_DATA_TYPE_BEGIN_CHILD(EventShop, "event_shop", 4)
		RUNTIME_DATA_TYPE_BEGIN_CHILD(EventShopItem, "item", 128)
			RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "slot_id")
			RUNTIME_DATA_PROPERTY(UInt64, ItemID, "item_id")
			RUNTIME_DATA_PROPERTY(UInt64, ItemOptions, "option")
			RUNTIME_DATA_PROPERTY(UInt8, ItemDurationID, "duration_id")
			RUNTIME_DATA_PROPERTY(UInt64, ItemPrice, "price")
			RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionForce, "item_option", 1)
				RUNTIME_DATA_PROPERTY(Int32, SlotCount, "slot_count")
				RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionForceSlot, "slot", 3)
					RUNTIME_DATA_PROPERTY(UInt8, Type, "type")
					RUNTIME_DATA_PROPERTY(UInt8, Slot, "slot")
					RUNTIME_DATA_PROPERTY(UInt8, Level, "level")
					RUNTIME_DATA_PROPERTY(UInt8, Option, "option")
				RUNTIME_DATA_TYPE_END_CHILD(ItemOptionForceSlot, 3)
			RUNTIME_DATA_TYPE_END_CHILD(ItemOptionForce, 1)
			RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionLevel, "item_level", 1)
				RUNTIME_DATA_PROPERTY(Int32, Level, "level")
			RUNTIME_DATA_TYPE_END_CHILD(ItemOptionLevel, 1)
			RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionArtifactSlot, "artifact_slot", 8)
				RUNTIME_DATA_PROPERTY(Int32, ForceLevel, "level")
				RUNTIME_DATA_PROPERTY(Int32, ForceIndex, "force")
			RUNTIME_DATA_TYPE_END_CHILD(ItemOptionArtifactSlot, 8)
		RUNTIME_DATA_TYPE_END_CHILD(EventShopItem, 128)
	RUNTIME_DATA_TYPE_END_CHILD(EventShop, 4)

	RUNTIME_DATA_TYPE_BEGIN_CHILD(EventItem, "event_item", 8)
		RUNTIME_DATA_PROPERTY(UInt64, ItemID, "item_id")
		RUNTIME_DATA_PROPERTY(UInt64, ItemOptions, "option")
		RUNTIME_DATA_PROPERTY(Int32, ExternalID, "external_id")
		RUNTIME_DATA_PROPERTY(UInt32, TextureItemID, "texture_item_id")
		RUNTIME_DATA_PROPERTY_ARRAY(Char, Title, "title", 260, '\0')
		RUNTIME_DATA_PROPERTY_ARRAY(Char, Description, "description", 260, '\0')
	RUNTIME_DATA_TYPE_END_CHILD(EventItem, 8)

RUNTIME_DATA_TYPE_END(Event)
RUNTIME_DATA_TYPE_INDEX(Event, Int32, ID)
RUNTIME_DATA_TYPE_INDEX_CHILD(EventShop, EventShopItem, Int32, SlotIndex)

RUNTIME_DATA_FILE_END
