RUNTIME_DATA_FILE_BEGIN(DIR_PATH(Event, Event.xml))

RUNTIME_DATA_TYPE_BEGIN(Event, "events.event")
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_PROPERTY(Int32, Type, "type")
	RUNTIME_DATA_PROPERTY(Int32, UseFlags, "use_flags")
	RUNTIME_DATA_PROPERTY(Int32, WorldIndex, "world_id")
	RUNTIME_DATA_PROPERTY(Int32, NpcIndex, "npc_id")
	RUNTIME_DATA_PROPERTY_ARRAY(Char, Description, "description", 260, '\0')

	RUNTIME_DATA_TYPE_BEGIN_CHILD(EventDescription, "event_description")
		RUNTIME_DATA_PROPERTY_ARRAY(Char, Description, "content", 260, '\0')
	RUNTIME_DATA_TYPE_END_CHILD(EventDescription)

	RUNTIME_DATA_TYPE_BEGIN_CHILD(EventShop, "event_shop")
		RUNTIME_DATA_TYPE_BEGIN_CHILD(EventShopItem, "item")
			RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "slot_id")
			RUNTIME_DATA_PROPERTY(UInt64, ItemID, "item_id")
			RUNTIME_DATA_PROPERTY(UInt64, ItemOptions, "option")
			RUNTIME_DATA_PROPERTY(UInt8, ItemDurationID, "duration_id")
			RUNTIME_DATA_PROPERTY(UInt64, ItemPrice, "price")
			RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionForce, "item_option")
				RUNTIME_DATA_PROPERTY(Int32, SlotCount, "slot_count")
				RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionForceSlot, "slot")
					RUNTIME_DATA_PROPERTY(UInt8, Type, "type")
					RUNTIME_DATA_PROPERTY(UInt8, Slot, "slot")
					RUNTIME_DATA_PROPERTY(UInt8, Level, "level")
					RUNTIME_DATA_PROPERTY(UInt8, Option, "option")
				RUNTIME_DATA_TYPE_END_CHILD(ItemOptionForceSlot)
			RUNTIME_DATA_TYPE_END_CHILD(ItemOptionForce)
			RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionLevel, "item_level")
				RUNTIME_DATA_PROPERTY(Int32, Level, "level")
			RUNTIME_DATA_TYPE_END_CHILD(ItemOptionLevel)
			RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionArtifactSlot, "artifact_slot")
				RUNTIME_DATA_PROPERTY(Int32, ForceLevel, "level")
				RUNTIME_DATA_PROPERTY(Int32, ForceIndex, "force")
			RUNTIME_DATA_TYPE_END_CHILD(ItemOptionArtifactSlot)
			RUNTIME_DATA_TYPE_BEGIN_CHILD(ItemOptionStack, "stack_option")
				RUNTIME_DATA_PROPERTY(Int32, Option, "option")
				RUNTIME_DATA_PROPERTY(Int32, StackSize, "stack_size")
			RUNTIME_DATA_TYPE_END_CHILD(ItemOptionStack)
		RUNTIME_DATA_TYPE_END_CHILD(EventShopItem)
	RUNTIME_DATA_TYPE_END_CHILD(EventShop)

	RUNTIME_DATA_TYPE_BEGIN_CHILD(EventItem, "event_item")
		RUNTIME_DATA_PROPERTY(UInt64, ItemID, "item_id")
		RUNTIME_DATA_PROPERTY(UInt64, ItemOptions, "option")
		RUNTIME_DATA_PROPERTY(Int32, ExternalID, "external_id")
		RUNTIME_DATA_PROPERTY(UInt32, TextureItemID, "texture_item_id")
		RUNTIME_DATA_PROPERTY_ARRAY(Char, Title, "title", 260, '\0')
		RUNTIME_DATA_PROPERTY_ARRAY(Char, Description, "description", 512, '\0')
		RUNTIME_DATA_PROPERTY_ARRAY(Char, Script, "script", 260, '\0')
	RUNTIME_DATA_TYPE_END_CHILD(EventItem)

RUNTIME_DATA_TYPE_END(Event)
RUNTIME_DATA_TYPE_INDEX(Event, Int32, ID)
RUNTIME_DATA_TYPE_INDEX_CHILD(EventShop, EventShopItem, Int32, SlotIndex)

RUNTIME_DATA_FILE_END
