RUNTIME_DATA_FILE_BEGIN(GiftBox.xml)

RUNTIME_DATA_TYPE_BEGIN(GiftBoxCondition, "GiftBox.Condition.GiftBox", 8)
	RUNTIME_DATA_PROPERTY(Int32, Index, "Index")
	RUNTIME_DATA_PROPERTY(Int32, IsEnabled, "IsEnabled")
	RUNTIME_DATA_PROPERTY(Int32, IsPremiumService, "IsPremiumService")
	RUNTIME_DATA_PROPERTY(Int32, IsPremiumPC, "IsPremiumPC")
	RUNTIME_DATA_PROPERTY(Int32, BlessingBeadIndex, "BlessingBeadIndex")
RUNTIME_DATA_TYPE_END(GiftBoxCondition)
RUNTIME_DATA_TYPE_INDEX(GiftBoxCondition, Int32, Index)

RUNTIME_DATA_TYPE_BEGIN(GiftBoxTimePool, "GiftBox.TimePool.Pool", 8)
	RUNTIME_DATA_PROPERTY(Int32, Index, "Index")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(GiftBoxTimePoolValue, "Time", 8)
		RUNTIME_DATA_PROPERTY(Int32, RequiredTime, "RequiredTime")
		RUNTIME_DATA_PROPERTY(Int32, Rate, "Rate")
	RUNTIME_DATA_TYPE_END_CHILD(GiftBoxTimePoolValue, 8)
RUNTIME_DATA_TYPE_END(GiftBoxTimePool)
RUNTIME_DATA_TYPE_INDEX(GiftBoxTimePool, Int32, Index)

RUNTIME_DATA_TYPE_BEGIN(GiftBoxRewardPool, "GiftBox.RewardPool.Pool", 8)
	RUNTIME_DATA_PROPERTY(Int32, Index, "Index")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(GiftBoxRewardPoolItem, "Item", 8)
		RUNTIME_DATA_PROPERTY(UInt64, ItemID, "ItemID")
		RUNTIME_DATA_PROPERTY(UInt64, ItemOption, "ItemOption")
		RUNTIME_DATA_PROPERTY(Int32, Rate, "Rate")
	RUNTIME_DATA_TYPE_END_CHILD(GiftBoxRewardPoolItem, 8)
RUNTIME_DATA_TYPE_END(GiftBoxRewardPool)
RUNTIME_DATA_TYPE_INDEX(GiftBoxRewardPool, Int32, Index)

RUNTIME_DATA_TYPE_BEGIN(GiftBoxPricePool, "GiftBox.PricePool.Pool", 8)
	RUNTIME_DATA_PROPERTY(Int32, Index, "Index")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(GiftBoxPricePoolValue, "Price", 32)
		RUNTIME_DATA_PROPERTY(Int32, OpenCount, "OpenCount")
		RUNTIME_DATA_PROPERTY(Int32, Price, "Price")
	RUNTIME_DATA_TYPE_END_CHILD(GiftBoxPricePoolValue, 32)
RUNTIME_DATA_TYPE_END(GiftBoxPricePool)
RUNTIME_DATA_TYPE_INDEX(GiftBoxPricePool, Int32, Index)
RUNTIME_DATA_TYPE_INDEX_CHILD(GiftBoxPricePool, GiftBoxPricePoolValue, Int32, OpenCount)

RUNTIME_DATA_FILE_END