RUNTIME_DATA_FILE_BEGIN(honor_medal.enc)

RUNTIME_DATA_TYPE_BEGIN(HonorMedalMain, "honor_medal_main.medal_main")
	RUNTIME_DATA_PROPERTY(Int32, Category, "Category")
	RUNTIME_DATA_PROPERTY(Int32, Type, "type")
	RUNTIME_DATA_PROPERTY(UInt64, RequiredHonorPoint, "needs")
RUNTIME_DATA_TYPE_END(HonorMedalMain)
RUNTIME_DATA_TYPE_INDEX(HonorMedalMain, Int32, Category)

RUNTIME_DATA_TYPE_BEGIN(HonorMedalBasicCategory, "honor_medal_main.honor_medal_basic.medal_category")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(HonorMedalBasicMedal, "medal")
		RUNTIME_DATA_PROPERTY(Int32, Group, "group")
		RUNTIME_DATA_PROPERTY(Int32, MinGrade, "min_grade")
		RUNTIME_DATA_PROPERTY(Int32, MaxGrade, "max_grade")
	RUNTIME_DATA_TYPE_END_CHILD(HonorMedalBasicMedal)
RUNTIME_DATA_TYPE_END(HonorMedalBasicCategory)
RUNTIME_DATA_TYPE_INDEX(HonorMedalBasicCategory, Int32, Category)
RUNTIME_DATA_TYPE_INDEX_CHILD(HonorMedalBasicCategory, HonorMedalBasicMedal, Int32, Group)

RUNTIME_DATA_TYPE_BEGIN(HonorMedalScoreCategory, "honor_medal_main.honor_medal_score.medal_category")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(HonorMedalScoreMedal, "medal")
		RUNTIME_DATA_PROPERTY(Int32, Group, "group")
		RUNTIME_DATA_PROPERTY(Int32, Grade, "grade")
		RUNTIME_DATA_PROPERTY(Int32, RequiredScore, "Reqscore")
		RUNTIME_DATA_PROPERTY(Int32, AccumulatedRequiredScore, "Areqscore")
		RUNTIME_DATA_PROPERTY(Int32, Value, "arcanum")
		RUNTIME_DATA_PROPERTY(Int32, Score, "bscore")
	RUNTIME_DATA_TYPE_END_CHILD(HonorMedalScoreMedal)
RUNTIME_DATA_TYPE_END(HonorMedalScoreCategory)
RUNTIME_DATA_TYPE_INDEX(HonorMedalScoreCategory, Int32, Category)

RUNTIME_DATA_TYPE_BEGIN(HonorMedalSlotCountCategory, "honor_medal_main.honor_medal_slot_count.medal_category")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(HonorMedalSlotCountMedal, "medal")
		RUNTIME_DATA_PROPERTY(Int32, Group, "group")
		RUNTIME_DATA_PROPERTY(Int32, SlotCount, "slot_count")
	RUNTIME_DATA_TYPE_END_CHILD(HonorMedalSlotCountMedal)
RUNTIME_DATA_TYPE_END(HonorMedalSlotCountCategory)
RUNTIME_DATA_TYPE_INDEX(HonorMedalSlotCountCategory, Int32, Category)
RUNTIME_DATA_TYPE_INDEX_CHILD(HonorMedalSlotCountCategory, HonorMedalSlotCountMedal, Int32, Group)

RUNTIME_DATA_TYPE_BEGIN(HonorMedalSlotOpenCategory, "honor_medal_main.honor_medal_slot_open.medal_category")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(HonorMedalSlotOpenMedal, "medal")
		RUNTIME_DATA_PROPERTY(Int32, Group, "group")
		RUNTIME_DATA_PROPERTY(UInt32, ItemID, "need_item")
		RUNTIME_DATA_PROPERTY(Int32, ItemCount, "need_count")
	RUNTIME_DATA_TYPE_END_CHILD(HonorMedalSlotOpenMedal)
RUNTIME_DATA_TYPE_END(HonorMedalSlotOpenCategory)
RUNTIME_DATA_TYPE_INDEX(HonorMedalSlotOpenCategory, Int32, Category)

RUNTIME_DATA_TYPE_BEGIN(HonorMedalSlotPriceCategory, "honor_medal_main.honor_medal_slot_price.medal_category")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(HonorMedalSlotPriceMedal, "medal")
		RUNTIME_DATA_PROPERTY(Int32, Group, "group")
		RUNTIME_DATA_PROPERTY(UInt32, WarExp, "WExp")
		RUNTIME_DATA_PROPERTY(Int32, AP, "AP")
	RUNTIME_DATA_TYPE_END_CHILD(HonorMedalSlotPriceMedal)
RUNTIME_DATA_TYPE_END(HonorMedalSlotPriceCategory)
RUNTIME_DATA_TYPE_INDEX(HonorMedalSlotPriceCategory, Int32, Category)
RUNTIME_DATA_TYPE_INDEX_CHILD(HonorMedalSlotPriceCategory, HonorMedalSlotPriceMedal, Int32, Group)

RUNTIME_DATA_TYPE_BEGIN(HonorMedalValueCategory, "honor_medal_main.honor_medal_value.medal_category")
	RUNTIME_DATA_PROPERTY(Int32, Category, "category")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(HonorMedalValueMedal, "medal")
		RUNTIME_DATA_PROPERTY(Int32, Group, "group")
		RUNTIME_DATA_PROPERTY(Int32, ForceID, "force_id")
		RUNTIME_DATA_PROPERTY(Int32, ValueType, "value_type")
		RUNTIME_DATA_PROPERTY(Int32, Value1, "value1")
		RUNTIME_DATA_PROPERTY(Int32, Value2, "value2")
		RUNTIME_DATA_PROPERTY(Int32, Value3, "value3")
		RUNTIME_DATA_PROPERTY(Int32, Value4, "value4")
		RUNTIME_DATA_PROPERTY(Int32, Value5, "value5")
		RUNTIME_DATA_PROPERTY(Int32, Value6, "value6")
		RUNTIME_DATA_PROPERTY(Int32, Value7, "value7")
		RUNTIME_DATA_PROPERTY(Int32, Value8, "value8")
		RUNTIME_DATA_PROPERTY(Int32, Value9, "value9")
		RUNTIME_DATA_PROPERTY(Int32, Value10, "value10")
	RUNTIME_DATA_TYPE_END_CHILD(HonorMedalValueMedal)
RUNTIME_DATA_TYPE_END(HonorMedalValueCategory)
RUNTIME_DATA_TYPE_INDEX(HonorMedalValueCategory, Int32, Category)

RUNTIME_DATA_TYPE_BEGIN(HonorMedalSeal, "honor_medal_main.honor_medal_seal.medal_seal")
	RUNTIME_DATA_PROPERTY(Int32, Option, "option")
	RUNTIME_DATA_PROPERTY(Int32, ForceEffectIndex, "force_id")
RUNTIME_DATA_TYPE_END(HonorMedalSeal)
RUNTIME_DATA_TYPE_INDEX(HonorMedalSeal, Int32, Option)
RUNTIME_DATA_TYPE_INDEX_SUFFIXED(HonorMedalSeal, ByForceID, Int32, ForceEffectIndex)

RUNTIME_DATA_FILE_END

RUNTIME_DATA_FILE_BEGIN(DIR_PATH(Character, HonorMedal.xml))

RUNTIME_DATA_TYPE_BEGIN(HonorMedalUpgradeCategory, "HonorMedal.Category")
	RUNTIME_DATA_PROPERTY(Int32, Category, "Index")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(HonorMedalUpgradeGroup, "Group")
		RUNTIME_DATA_PROPERTY(Int32, Group, "Index")
		RUNTIME_DATA_TYPE_BEGIN_CHILD(HonorMedalUpgradeMedal, "Medal")
			RUNTIME_DATA_PROPERTY(Int32, ForceEffectIndex, "ForceIndex")
			RUNTIME_DATA_PROPERTY(Int32, Rate, "Rate")
		RUNTIME_DATA_TYPE_END_CHILD(HonorMedalUpgradeMedal)
	RUNTIME_DATA_TYPE_END_CHILD(HonorMedalUpgradeGroup)
RUNTIME_DATA_TYPE_END(HonorMedalUpgradeCategory)
RUNTIME_DATA_TYPE_INDEX(HonorMedalUpgradeCategory, Int32, Category)
RUNTIME_DATA_TYPE_INDEX_CHILD(HonorMedalUpgradeCategory, HonorMedalUpgradeGroup, Int32, Group)

RUNTIME_DATA_FILE_END

