RUNTIME_DATA_FILE_BEGIN(level.enc)

RUNTIME_DATA_TYPE_BEGIN(Level, "Level.level_up.con", 256)
	RUNTIME_DATA_PROPERTY(Int32, Level, "level")
	RUNTIME_DATA_PROPERTY(Int32, Exp, "exp")
	RUNTIME_DATA_PROPERTY(Int32, AccumulatedExp, "accuexp")
RUNTIME_DATA_TYPE_END(Level)
RUNTIME_DATA_TYPE_INDEX(Level, Int32, Level)

RUNTIME_DATA_FILE_END