RUNTIME_DATA_FILE_BEGIN(level.enc)

RUNTIME_DATA_TYPE_BEGIN(Level, "Level.level_up.con", 256)
	RUNTIME_DATA_PROPERTY(Int32, Level, "level")
	RUNTIME_DATA_PROPERTY(UInt64, Exp, "exp")
	RUNTIME_DATA_PROPERTY(UInt64, AccumulatedExp, "accuexp")
RUNTIME_DATA_TYPE_END(Level)
RUNTIME_DATA_TYPE_INDEX(Level, Int32, Level)

RUNTIME_DATA_FILE_END

RUNTIME_DATA_FILE_BEGIN(LevelRewardPool.xml)

RUNTIME_DATA_TYPE_BEGIN(LevelReward, "LevelRewardPool.Reward", 32)
	RUNTIME_DATA_PROPERTY(Int32, Level, "Level")
	RUNTIME_DATA_PROPERTY(UInt32, MapCode, "MapCode")
	RUNTIME_DATA_PROPERTY(UInt32, WarpCode, "WarpCode")
RUNTIME_DATA_TYPE_END(LevelReward)
RUNTIME_DATA_TYPE_INDEX(LevelReward, Int32, Level)

RUNTIME_DATA_FILE_END
