RUNTIME_DATA_FILE_BEGIN(market.enc)

RUNTIME_DATA_TYPE_BEGIN(MarketCategoryMainGroup, "cabal_market.market_category.main_group")
	RUNTIME_DATA_PROPERTY(Int32, Category1, "g1id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MarketCategorySubGroup, "sub_group")
		RUNTIME_DATA_PROPERTY(Int32, Order, "order1")
		RUNTIME_DATA_PROPERTY(Int32, Category2, "g2id")
		RUNTIME_DATA_TYPE_BEGIN_CHILD(MarketCategorySetList, "set_list")
			RUNTIME_DATA_PROPERTY(Int32, Order, "order")
			RUNTIME_DATA_PROPERTY(Int32, Set1, "set1id")
			RUNTIME_DATA_PROPERTY(Int32, Set2, "set2id")
			RUNTIME_DATA_PROPERTY(Int32, Set3, "set3id")
		RUNTIME_DATA_TYPE_END_CHILD(MarketCategorySetList)
	RUNTIME_DATA_TYPE_END_CHILD(MarketCategorySubGroup)
RUNTIME_DATA_TYPE_END(MarketCategoryMainGroup)
RUNTIME_DATA_TYPE_INDEX(MarketCategoryMainGroup, Int32, Category1)

RUNTIME_DATA_TYPE_BEGIN(MarketCategoryMainSet1, "cabal_market.market_set1.main_set")
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MarketCategorySubSet1, "sub_set")
		RUNTIME_DATA_PROPERTY(Int32, Order, "order")
		RUNTIME_DATA_PROPERTY(Int32, Category3, "g3id")
	RUNTIME_DATA_TYPE_END_CHILD(MarketCategorySubSet1)
RUNTIME_DATA_TYPE_END(MarketCategoryMainSet1)
RUNTIME_DATA_TYPE_INDEX(MarketCategoryMainSet1, Int32, ID)

RUNTIME_DATA_TYPE_BEGIN(MarketCategoryMainSet2, "cabal_market.market_set2.main_set")
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MarketCategorySubSet2, "sub_set")
		RUNTIME_DATA_PROPERTY(Int32, Order, "order")
		RUNTIME_DATA_PROPERTY(Int32, Category4, "g4id")
	RUNTIME_DATA_TYPE_END_CHILD(MarketCategorySubSet2)
RUNTIME_DATA_TYPE_END(MarketCategoryMainSet2)
RUNTIME_DATA_TYPE_INDEX(MarketCategoryMainSet2, Int32, ID)

RUNTIME_DATA_TYPE_BEGIN(MarketCategoryMainSet3, "cabal_market.market_set3.main_set")
	RUNTIME_DATA_PROPERTY(Int32, ID, "id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MarketCategorySubSet3, "sub_set")
		RUNTIME_DATA_PROPERTY(Int32, Order, "order")
		RUNTIME_DATA_PROPERTY(Int32, Category5, "g5id")
	RUNTIME_DATA_TYPE_END_CHILD(MarketCategorySubSet3)
RUNTIME_DATA_TYPE_END(MarketCategoryMainSet3)
RUNTIME_DATA_TYPE_INDEX(MarketCategoryMainSet3, Int32, ID)

RUNTIME_DATA_TYPE_BEGIN(MarketCommission, "cabal_market.commission")
	RUNTIME_DATA_PROPERTY(Int32, Base, "base")
	RUNTIME_DATA_PROPERTY(Int32, Control, "control")
	RUNTIME_DATA_PROPERTY(Int32, Step, "step")
RUNTIME_DATA_TYPE_END(MarketCommission)
RUNTIME_DATA_TYPE_INDEX_SINGLE(MarketCommission)

RUNTIME_DATA_TYPE_BEGIN(MarketListItem, "cabal_market.market_list.list")
	RUNTIME_DATA_PROPERTY(UInt64, ItemID, "item_id")
	RUNTIME_DATA_PROPERTY(UInt64, ItemOptions, "item_opt")
	RUNTIME_DATA_PROPERTY(Int32, Category2, "g2id")
	RUNTIME_DATA_PROPERTY(Int32, Category3, "g3id")
	RUNTIME_DATA_PROPERTY(Int32, Category4, "g4id")
RUNTIME_DATA_TYPE_END(MarketListItem)

RUNTIME_DATA_FILE_END
