RUNTIME_DATA_FILE_BEGIN(meritsystem.enc)

RUNTIME_DATA_TYPE_BEGIN(GoldMeritScoreFormula, "cabal_merit_system.meritscore_fomula.meritscore")
	RUNTIME_DATA_PROPERTY(Int32, MinScore, "min")
	RUNTIME_DATA_PROPERTY(Int32, MaxScore, "max")
	RUNTIME_DATA_PROPERTY(Int32, RewardPoints, "reward_meritpoint")
RUNTIME_DATA_TYPE_END(GoldMeritScoreFormula)
RUNTIME_DATA_TYPE_INDEX_RANGE(GoldMeritScoreFormula, Int32, MinScore, MaxScore)

RUNTIME_DATA_TYPE_BEGIN(PlatinumMeritScoreFormula, "cabal_merit_system.extend_meritscore_fomula.meritscore")
	RUNTIME_DATA_PROPERTY(Int32, MinScore, "min")
	RUNTIME_DATA_PROPERTY(Int32, MaxScore, "max")
	RUNTIME_DATA_PROPERTY(Int32, RewardPoints, "reward_meritpoint")
RUNTIME_DATA_TYPE_END(PlatinumMeritScoreFormula)
RUNTIME_DATA_TYPE_INDEX_RANGE(PlatinumMeritScoreFormula, Int32, MinScore, MaxScore)

RUNTIME_DATA_TYPE_BEGIN(DiamondMeritScoreFormula, "cabal_merit_system.dia_meritscore_fomula.meritscore")
	RUNTIME_DATA_PROPERTY(Int32, MinScore, "min")
	RUNTIME_DATA_PROPERTY(Int32, MaxScore, "max")
	RUNTIME_DATA_PROPERTY(Int32, RewardPoints, "reward_meritpoint")
RUNTIME_DATA_TYPE_END(DiamondMeritScoreFormula)
RUNTIME_DATA_TYPE_INDEX_RANGE(DiamondMeritScoreFormula, Int32, MinScore, MaxScore)

RUNTIME_DATA_TYPE_BEGIN(MeritMedalEvaluationFee, "cabal_merit_system.trophyevaluation_fee.trophyevaluation")
	RUNTIME_DATA_PROPERTY(Int32, Type, "type")
	RUNTIME_DATA_PROPERTY(Int32, EvaluationCount, "count")
	RUNTIME_DATA_PROPERTY(Int32, RequiredWexp, "needs_wexp")
RUNTIME_DATA_TYPE_END(MeritMedalEvaluationFee)
RUNTIME_DATA_TYPE_INDEX_PAIR(MeritMedalEvaluationFee, Int32, Type, Int32, EvaluationCount)

RUNTIME_DATA_TYPE_BEGIN(MeritMedalRewardScore, "cabal_merit_system.trophyreward_meritscore.reward_meritscore")
	RUNTIME_DATA_PROPERTY(Int32, MedalGrade, "trophy_grade")
	RUNTIME_DATA_PROPERTY(Int32, RewardScore, "meritscore")
RUNTIME_DATA_TYPE_END(MeritMedalRewardScore)
RUNTIME_DATA_TYPE_INDEX(MeritMedalRewardScore, Int32, MedalGrade)

RUNTIME_DATA_TYPE_BEGIN(MeritMedalRewardHonor, "cabal_merit_system.trophyreward_reputation.reward_reputation")
	RUNTIME_DATA_PROPERTY(Int32, GradeType, "grade_type")
	RUNTIME_DATA_PROPERTY(Int32, MedalGrade, "trophy_grade")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank10, "grade10")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank11, "grade11")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank12, "grade12")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank13, "grade13")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank14, "grade14")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank15, "grade15")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank16, "grade16")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank17, "grade17")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank18, "grade18")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank19, "grade19")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank20, "grade20")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank21, "grade21")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank22, "grade22")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank23, "grade23")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank24, "grade24")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank25, "grade25")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank26, "grade26")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank27, "grade27")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank28, "grade28")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank29, "grade29")
	RUNTIME_DATA_PROPERTY(Int32, HonorRank30, "grade30")
RUNTIME_DATA_TYPE_END(MeritMedalRewardHonor)
RUNTIME_DATA_TYPE_INDEX_PAIR(MeritMedalRewardHonor, Int32, GradeType, Int32, MedalGrade)

RUNTIME_DATA_TYPE_BEGIN(MeritMasteryCategory, "cabal_merit_system.meritmastery_base.mastery_category")
	RUNTIME_DATA_PROPERTY(Int32, Index, "index")
	RUNTIME_DATA_PROPERTY(Int32, Grade, "Badge_Grade")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MeritMasteryBase, "mastery_base")
		RUNTIME_DATA_PROPERTY(Int32, MasteryIndex, "mastery_index")
		RUNTIME_DATA_PROPERTY(Int32, MasteryType, "mastery_type")
		RUNTIME_DATA_PROPERTY(Int32, MaxLevel, "max_level")
		RUNTIME_DATA_PROPERTY(Int32, PreMasteryIndex, "premastery_index")
		RUNTIME_DATA_PROPERTY(Int32, PreMasteryMinLevel, "premastery_reqlevel")
		RUNTIME_DATA_PROPERTY(Int32, LinkedMasteryIndex, "linkedmastery_index")
	RUNTIME_DATA_TYPE_END_CHILD(MeritMasteryBase)
RUNTIME_DATA_TYPE_END(MeritMasteryCategory)

RUNTIME_DATA_TYPE_BEGIN(MeritMasteryValue, "cabal_merit_system.meritmastery_value.mastery")
	RUNTIME_DATA_PROPERTY(Int32, Index, "index")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MeritMasteryValueLevel, "value")
		RUNTIME_DATA_PROPERTY(Int32, MasteryLevel, "mastery_level")
		RUNTIME_DATA_PROPERTY(Int32, RequiredMeritPoints, "req_meritpoint")
		RUNTIME_DATA_PROPERTY(Int32, BaseForceEffectIndex, "base_forceid")
		RUNTIME_DATA_PROPERTY(Int32, BaseForceValue, "base_forcevalue")
		RUNTIME_DATA_PROPERTY(Int32, BaseForceValueType, "base_valuetype")
		RUNTIME_DATA_PROPERTY(Int32, BonusForceEffectIndex, "bonus_forceid")
		RUNTIME_DATA_PROPERTY(Int32, BonusForceValue, "bonus_forcevalue")
		RUNTIME_DATA_PROPERTY(Int32, BonusForceValueType, "bonus_valuetype")
	RUNTIME_DATA_TYPE_END_CHILD(MeritMasteryValueLevel)
RUNTIME_DATA_TYPE_END(MeritMasteryValue)
RUNTIME_DATA_TYPE_INDEX(MeritMasteryValue, Int32, Index)

RUNTIME_DATA_TYPE_BEGIN(MeritMasteryGrade, "cabal_merit_system.UpGrade_Material.UpGrade")
	RUNTIME_DATA_PROPERTY(Int32, Grade, "upgrade_badge")
	RUNTIME_DATA_PROPERTY(Int32, RequiredWexp, "upgrade_wexp")
	RUNTIME_DATA_PROPERTY(UInt64, RequiredItemID, "upgrade_item")
	RUNTIME_DATA_PROPERTY(UInt64, RequiredItemCount, "upgrade_count")
RUNTIME_DATA_TYPE_END(MeritMasteryGrade)
RUNTIME_DATA_TYPE_INDEX(MeritMasteryGrade, Int32, Grade)

RUNTIME_DATA_TYPE_BEGIN(MeritMasterySlotOpenCategory, "cabal_merit_system.SlotOpen_Material.Category")
	RUNTIME_DATA_PROPERTY(Int32, Category, "Num")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MeritMasterySlotOpenMaterial, "Opend")
		RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "Slot")
		RUNTIME_DATA_PROPERTY(Int32, SortingOrder, "Order")
		RUNTIME_DATA_PROPERTY(UInt64, RequiredItemID, "Need_Item")
		RUNTIME_DATA_PROPERTY(UInt64, RequiredItemCount, "Need_Count")
	RUNTIME_DATA_TYPE_END_CHILD(MeritMasterySlotOpenMaterial)
RUNTIME_DATA_TYPE_END(MeritMasterySlotOpenCategory)
RUNTIME_DATA_TYPE_INDEX(MeritMasterySlotOpenCategory, Int32, Category)
RUNTIME_DATA_TYPE_INDEX_CHILD_PAIR(MeritMasterySlotOpenCategory, MeritMasterySlotOpenMaterial, Int32, SlotIndex, Int32, SortingOrder)

RUNTIME_DATA_TYPE_BEGIN(MeritMasterySlotOpenTime, "cabal_merit_system.SlotOpen_Time.SlotOpenTime")
	RUNTIME_DATA_PROPERTY(Int32, Category, "Category_Num")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "Opened_Slot")
	RUNTIME_DATA_PROPERTY(UInt64, OpenTime, "Need_Time")
RUNTIME_DATA_TYPE_END(MeritMasterySlotOpenTime)
RUNTIME_DATA_TYPE_INDEX_PAIR(MeritMasterySlotOpenTime, Int32, Category, Int32, SlotIndex)

RUNTIME_DATA_TYPE_BEGIN(MeritMasterySpecialMasteryMaterial, "cabal_merit_system.SpecialMastery_Material.Material")
	RUNTIME_DATA_PROPERTY(Int32, Grade, "Mastery_type")
	RUNTIME_DATA_PROPERTY(Int32, RequiredWexp, "wexp")
	RUNTIME_DATA_PROPERTY(UInt64, RequiredItemID, "Need_Item")
	RUNTIME_DATA_PROPERTY(UInt64, RequiredItemCount, "Need_Count")
RUNTIME_DATA_TYPE_END(MeritMasterySpecialMasteryMaterial)
RUNTIME_DATA_TYPE_INDEX(MeritMasterySpecialMasteryMaterial, Int32, Grade)

RUNTIME_DATA_TYPE_BEGIN(MeritMasterySpecialMasteryValue, "cabal_merit_system.SpecialMastery_Value.SpecialMasteryValue")
	RUNTIME_DATA_PROPERTY(Int32, Category, "Category_Num")
	RUNTIME_DATA_PROPERTY(Int32, MasteryIndex, "SpecialMastery_Index")
	RUNTIME_DATA_PROPERTY(Int32, MasteryGrade, "Grade")
	RUNTIME_DATA_PROPERTY(Int32, ForceEffectIndex, "Force_ID")
	RUNTIME_DATA_PROPERTY(Int32, ForceEffectValue, "Force_Value")
	RUNTIME_DATA_PROPERTY(Int32, ForceEffectValueType, "Force_ValueType")
RUNTIME_DATA_TYPE_END(MeritMasterySpecialMasteryValue)

RUNTIME_DATA_TYPE_BEGIN(MeritMasteryGroup, "cabal_merit_system.MasteryIndex_Group.MasteryGroup")
	RUNTIME_DATA_PROPERTY(Int32, MasteryType, "Merit_type")
	RUNTIME_DATA_PROPERTY(Int32, Category, "Category")
	RUNTIME_DATA_PROPERTY_ARRAY(Int32, MasteryIndex, "MasteryIndex", 3, ',')
RUNTIME_DATA_TYPE_END(MeritMasteryGroup)
RUNTIME_DATA_TYPE_INDEX_PAIR(MeritMasteryGroup, Int32, MasteryType, Int32, Category)

RUNTIME_DATA_FILE_END

RUNTIME_DATA_FILE_BEGIN(DIR_PATH(Loot, MeritMasteryPool.xml))

RUNTIME_DATA_TYPE_BEGIN(MeritMasterySpecialMasteryPool, "MeritMasteryPool.SpecialMasteryPool")
	RUNTIME_DATA_PROPERTY(Int32, Grade, "Grade")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MeritMasterySpecialMasteryPoolCategory, "Category")
		RUNTIME_DATA_PROPERTY(Int32, Index, "Index")
		RUNTIME_DATA_TYPE_BEGIN_CHILD(MeritMasterySpecialMasteryPoolMastery, "Mastery")
			RUNTIME_DATA_PROPERTY(Int32, Index, "Index")
			RUNTIME_DATA_TYPE_BEGIN_CHILD(MeritMasterySpecialMasteryPoolOption, "Option")
				RUNTIME_DATA_PROPERTY(Int32, Grade, "Grade")
				RUNTIME_DATA_PROPERTY(Int32, Rate, "Rate")
				RUNTIME_DATA_PROPERTY(Int32, RewardExp, "RewardExp")
			RUNTIME_DATA_TYPE_END_CHILD(MeritMasterySpecialMasteryPoolOption)
		RUNTIME_DATA_TYPE_END_CHILD(MeritMasterySpecialMasteryPoolMastery)
	RUNTIME_DATA_TYPE_END_CHILD(MeritMasterySpecialMasteryPoolCategory)
RUNTIME_DATA_TYPE_END(MeritMasterySpecialMasteryPool)
RUNTIME_DATA_TYPE_INDEX(MeritMasterySpecialMasteryPool, Int32, Grade)
RUNTIME_DATA_TYPE_INDEX_CHILD(MeritMasterySpecialMasteryPool, MeritMasterySpecialMasteryPoolCategory, Int32, Index)

RUNTIME_DATA_FILE_END

RUNTIME_DATA_FILE_BEGIN(DIR_PATH(Loot, MeritItemPool.xml))

RUNTIME_DATA_TYPE_BEGIN(MeritItemPool, "MeritItemPool.Pool")
	RUNTIME_DATA_PROPERTY(Int32, Type, "Type")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MeritItemPoolGroup, "ItemGroup")
		RUNTIME_DATA_PROPERTY(Int32, EvaluationCount, "EvaluationCount")
		RUNTIME_DATA_TYPE_BEGIN_CHILD(MeritItemPoolGroupItem, "Item")
			RUNTIME_DATA_PROPERTY_ARRAY(UInt64, ItemIDs, "ItemIDs", 3, ',')
			RUNTIME_DATA_PROPERTY(Int32, Rate, "Rate")
		RUNTIME_DATA_TYPE_END_CHILD(MeritItemPoolGroupItem)
	RUNTIME_DATA_TYPE_END_CHILD(MeritItemPoolGroup)
RUNTIME_DATA_TYPE_END(MeritItemPool)
RUNTIME_DATA_TYPE_INDEX(MeritItemPool, Int32, Type)
RUNTIME_DATA_TYPE_INDEX_CHILD(MeritItemPool, MeritItemPoolGroup, Int32, EvaluationCount)

RUNTIME_DATA_FILE_END
