RUNTIME_DATA_FILE_BEGIN(smob.enc)

RUNTIME_DATA_TYPE_BEGIN(MobAttack, "cabal_mob.attack_main.attack")
	RUNTIME_DATA_PROPERTY(UInt32, ID, "id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MobAttackData, "attack_data")
		RUNTIME_DATA_PROPERTY(Int32, AttackType, "attack_type")
		RUNTIME_DATA_PROPERTY(Int32, RangeType, "range_type")
		RUNTIME_DATA_PROPERTY(Int32, Reach, "reach")
		RUNTIME_DATA_PROPERTY(Int32, Range, "atk_range")
		RUNTIME_DATA_PROPERTY(Int32, RangeMark, "range_mark")
		RUNTIME_DATA_PROPERTY(Int32, SkillID, "mob_skill")
		RUNTIME_DATA_PROPERTY(Int32, SkillLevel, "mob_skill_lv")
		RUNTIME_DATA_PROPERTY(Int32, SkillDuration, "mob_skill_dur")
		RUNTIME_DATA_PROPERTY(Int32, BfxID, "bfx_id")
		RUNTIME_DATA_PROPERTY_ARRAY(Int32, BfxDuration, "bfx_dur", 2, ',')
		RUNTIME_DATA_PROPERTY_ARRAY(Int32, Power, "power", 2, ',')
		RUNTIME_DATA_PROPERTY(Int32, BfxChangeDir, "bfx_change_dir")
		RUNTIME_DATA_PROPERTY(Int32, NoFlinch, "no_flinch")
	RUNTIME_DATA_TYPE_END_CHILD(MobAttackData)
RUNTIME_DATA_TYPE_END(MobAttack)
RUNTIME_DATA_TYPE_INDEX(MobAttack, UInt32, ID)

RUNTIME_DATA_TYPE_BEGIN(MobSkill, "cabal_mob.mob_skill.mob_skill_value")
	RUNTIME_DATA_PROPERTY(UInt32, ID, "id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MobSkillValue, "value")
		RUNTIME_DATA_PROPERTY(Int32, ForceID, "bforce_id")
		RUNTIME_DATA_PROPERTY_ARRAY(Int32, ForceValue, "bforce_value", 3, ',')
		RUNTIME_DATA_PROPERTY_ARRAY(Int32, Power, "power", 2, ',')
		RUNTIME_DATA_PROPERTY(Int32, ValueType, "value_type")
	RUNTIME_DATA_TYPE_END_CHILD(MobSkillValue)
RUNTIME_DATA_TYPE_END(MobSkill)
RUNTIME_DATA_TYPE_INDEX(MobSkill, UInt32, ID)

RUNTIME_DATA_TYPE_BEGIN(MobAttackIndex, "cabal_mob.mob_atk_index.mob_num")
	RUNTIME_DATA_PROPERTY(UInt32, MobID, "speciesIdx")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MobAttackLink, "mob_atk_link")
		RUNTIME_DATA_PROPERTY(Int32, MobAttackID, "attack_num")
	RUNTIME_DATA_TYPE_END_CHILD(MobAttackLink)
RUNTIME_DATA_TYPE_END(MobAttackIndex)
RUNTIME_DATA_TYPE_INDEX(MobAttackIndex, UInt32, MobID)

RUNTIME_DATA_TYPE_BEGIN(MobEffectIndex, "cabal_mob.mob_efx_index.mob_num")
	RUNTIME_DATA_PROPERTY(UInt32, MobID, "speciesIdx")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MobEffectLink, "mob_efx_link")
		RUNTIME_DATA_PROPERTY(Int32, MobEffectID, "effect_num")
	RUNTIME_DATA_TYPE_END_CHILD(MobEffectLink)
RUNTIME_DATA_TYPE_END(MobEffectIndex)
RUNTIME_DATA_TYPE_INDEX(MobEffectIndex, UInt32, MobID)

RUNTIME_DATA_FILE_END
