RUNTIME_DATA_FILE_BEGIN(Myth.enc)

RUNTIME_DATA_TYPE_BEGIN(MythMain, "Myth.Myth_main.Condition")
	RUNTIME_DATA_PROPERTY(Int32, OverlordLevel, "Olv")
	RUNTIME_DATA_PROPERTY(Int32, RequiredQuest, "Prequest")
RUNTIME_DATA_TYPE_END(MythMain)
RUNTIME_DATA_TYPE_INDEX_SINGLE(MythMain)

RUNTIME_DATA_TYPE_BEGIN(MythLevel, "Myth.Myth_Level.Myth_Exp")
	RUNTIME_DATA_PROPERTY(Int32, MythLevel, "MLV")
	RUNTIME_DATA_PROPERTY(UInt64, RequiredExp, "ReqExp")
	RUNTIME_DATA_PROPERTY(Int32, MythPoints, "Myth_point")
RUNTIME_DATA_TYPE_END(MythLevel)
RUNTIME_DATA_TYPE_INDEX(MythLevel, Int32, MythLevel)

RUNTIME_DATA_TYPE_BEGIN(MythMax, "Myth.Max_info.info")
	RUNTIME_DATA_PROPERTY(Int32, MaxMythLevel, "MaxMLV")
	RUNTIME_DATA_PROPERTY(Int32, MaxPoints, "MaxPoint")
RUNTIME_DATA_TYPE_END(MythMax)
RUNTIME_DATA_TYPE_INDEX_SINGLE(MythMax)

RUNTIME_DATA_TYPE_BEGIN(MythReset, "Myth.Reset.Reset_condition")
	RUNTIME_DATA_PROPERTY(Int32, RequiredLevel, "Lv")
RUNTIME_DATA_TYPE_END(MythReset)
RUNTIME_DATA_TYPE_INDEX_SINGLE(MythReset)

RUNTIME_DATA_TYPE_BEGIN(MythRepeat, "Myth.Repeat.Repeat_Bonus")
	RUNTIME_DATA_PROPERTY(Int32, RepeatCondition, "Repeat_condition")
	RUNTIME_DATA_PROPERTY(Int32, BonusPoints, "Bonus_Pt")
RUNTIME_DATA_TYPE_END(MythRepeat)
RUNTIME_DATA_TYPE_INDEX_SINGLE(MythRepeat)

RUNTIME_DATA_TYPE_BEGIN(MythRepeatPenalty, "Myth.RepeatPenalty.Penaltyinfo")
	RUNTIME_DATA_PROPERTY(Int32, AddMxp, "AddMxp")
	RUNTIME_DATA_PROPERTY(Int32, Limit, "Limit")
RUNTIME_DATA_TYPE_END(MythRepeatPenalty)
RUNTIME_DATA_TYPE_INDEX_SINGLE(MythRepeatPenalty)

RUNTIME_DATA_TYPE_BEGIN(MythRestoreItem, "Myth.Restore.RestoreItem")
	RUNTIME_DATA_PROPERTY(UInt32, ItemID, "itemidx")
RUNTIME_DATA_TYPE_END(MythRestoreItem)
RUNTIME_DATA_TYPE_INDEX_SINGLE(MythRestoreItem)

RUNTIME_DATA_TYPE_BEGIN(MythSlotPage, "Myth.Myth_Mastery.SlotPage")
	RUNTIME_DATA_PROPERTY(Int32, MasteryIndex, "Mastery_idx")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(SlotInfo, "SlotInfo")
		RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "Slot_idx")
		RUNTIME_DATA_PROPERTY(Int32, Type, "Slot_type")
		RUNTIME_DATA_PROPERTY(Int32, LockGroup, "Lock_group")
		RUNTIME_DATA_PROPERTY(Int32, PrerequisiteSlot, "Pre_Slot")
		RUNTIME_DATA_PROPERTY(Int32, PrerequisiteSlot2, "Pre_Slot2")
		RUNTIME_DATA_PROPERTY(Int32, UnlockCost, "Cost_Point")
		RUNTIME_DATA_PROPERTY(Int32, RestoreCost, "Restore_cost")
	RUNTIME_DATA_TYPE_END_CHILD(SlotInfo)
RUNTIME_DATA_TYPE_END(MythSlotPage)
RUNTIME_DATA_TYPE_INDEX(MythSlotPage, Int32, MasteryIndex)
RUNTIME_DATA_TYPE_INDEX_CHILD(MythSlotPage, SlotInfo, Int32, SlotIndex)

RUNTIME_DATA_TYPE_BEGIN(MythLockPage, "Myth.Lock.SlotPage")
	RUNTIME_DATA_PROPERTY(Int32, MasteryIndex, "Mastery_idx")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MythLockInfo, "LockInfo")
		RUNTIME_DATA_PROPERTY(Int32, LockGroup, "Lock_group")
		RUNTIME_DATA_PROPERTY(Int32, OpenScore, "Open_score")
		RUNTIME_DATA_PROPERTY(Int32, BonusScore, "Bonus_score")
	RUNTIME_DATA_TYPE_END_CHILD(MythLockInfo)
RUNTIME_DATA_TYPE_END(MythLockPage)
RUNTIME_DATA_TYPE_INDEX(MythLockPage, Int32, MasteryIndex)
RUNTIME_DATA_TYPE_INDEX_CHILD(MythLockPage, MythLockInfo, Int32, LockGroup)

RUNTIME_DATA_FILE_END

RUNTIME_DATA_FILE_BEGIN(DIR_PATH(Character, MythMastery.xml))

RUNTIME_DATA_TYPE_BEGIN(MythSlotGroupPool, "MythMastery.SlotGroupPool.Pool")
RUNTIME_DATA_PROPERTY(Int32, GroupID, "ID")
RUNTIME_DATA_PROPERTY(Int32, MythSlotValuePoolID, "SlotValuePoolIndex")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MythSlotGroup, "SlotGroup")
	RUNTIME_DATA_PROPERTY(Int32, GroupID, "ID")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(MythSlotIndexGroup, "SlotIndexGroup")
		RUNTIME_DATA_PROPERTY(UInt32, MasteryIndex, "MasteryIndex")
		RUNTIME_DATA_PROPERTY(UInt32, SlotIndex, "SlotIndex")
	RUNTIME_DATA_TYPE_END_CHILD(MythSlotIndexGroup)
RUNTIME_DATA_TYPE_END_CHILD(MythSlotGroup)
RUNTIME_DATA_TYPE_END(MythSlotGroupPool)
RUNTIME_DATA_TYPE_INDEX(MythSlotGroupPool, Int32, GroupID)
RUNTIME_DATA_TYPE_INDEX_CHILD(MythSlotGroupPool, MythSlotGroup, UInt32, GroupID)

RUNTIME_DATA_TYPE_BEGIN(MythSlotGroupValuePool, "MythMastery.SlotValuePoolGroup.Pool")
RUNTIME_DATA_PROPERTY(Int32, PoolID, "ID")
RUNTIME_DATA_TYPE_BEGIN_CHILD(MythSlotValuePool, "MythSlotValue")
	RUNTIME_DATA_PROPERTY(UInt32, ForceCode, "ForceID")
	RUNTIME_DATA_PROPERTY(UInt32, Value, "Value")
	RUNTIME_DATA_PROPERTY(UInt32, ValueType, "ValueType")
	RUNTIME_DATA_PROPERTY(UInt32, Grade, "Grade")
	RUNTIME_DATA_PROPERTY(UInt32, Chance, "Rate")
RUNTIME_DATA_TYPE_END_CHILD(MythSlotValuePool)
RUNTIME_DATA_TYPE_END(MythSlotGroupValuePool)
RUNTIME_DATA_TYPE_INDEX(MythSlotValuePool, Int32, PoolID)
RUNTIME_DATA_TYPE_INDEX_CHILD(MythSlotGroupValuePool, MythSlotValuePool, UInt32, PoolID)

RUNTIME_DATA_FILE_END