#ifndef RUNTIME_DATA_NEWBIE_SUPPORT_CATEGORY_TYPE
#define RUNTIME_DATA_NEWBIE_SUPPORT_CATEGORY_TYPE

enum {
	RUNTIME_NEWBIE_SUPPORT_CATEGORY_TYPE_LEVEL = 0,
	RUNTIME_NEWBIE_SUPPORT_CATEGORY_TYPE_SKILL_RANK = 1,
	RUNTIME_NEWBIE_SUPPORT_CATEGORY_TYPE_HONOR_RANK = 2,

	RUNTIME_NEWBIE_SUPPORT_CATEGORY_TYPE_COUNT,
};

#endif

RUNTIME_DATA_FILE_BEGIN(NewbieSupport.enc)

RUNTIME_DATA_TYPE_BEGIN(NewbieSupportCategory, "NewbieSupport.Category")
	RUNTIME_DATA_PROPERTY(Int32, Type, "Type")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(NewbieSupportCategoryReward, "Reward")
		RUNTIME_DATA_PROPERTY(Int32, ConditionValue1, "ConditionValue1")
		RUNTIME_DATA_PROPERTY(Int32, ConditionValue2, "ConditionValue2")
		RUNTIME_DATA_PROPERTY(Int32, RewardID, "RewardID")
	RUNTIME_DATA_TYPE_END_CHILD(NewbieSupportCategoryReward)
RUNTIME_DATA_TYPE_END(NewbieSupportCategory)
RUNTIME_DATA_TYPE_INDEX(NewbieSupportCategory, Int32, Type)

RUNTIME_DATA_TYPE_BEGIN(NewbieSupportRewardPool, "NewbieSupport.RewardPool")
	RUNTIME_DATA_PROPERTY(Int32, RewardID, "RewardID")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(NewbieSupportRewardPoolItem, "List")
		RUNTIME_DATA_PROPERTY(Int32, Order, "Order")
		RUNTIME_DATA_PROPERTY(UInt32, BattleStyleFlag, "BSFlag")
		RUNTIME_DATA_PROPERTY(UInt64, ItemID, "ItenKind")
		RUNTIME_DATA_PROPERTY(UInt64, ItemOptions, "Option")
		RUNTIME_DATA_PROPERTY(UInt32, ItemDuration, "Duration")
		RUNTIME_DATA_PROPERTY(Int32, Count, "Count")
	RUNTIME_DATA_TYPE_END_CHILD(NewbieSupportRewardPoolItem)
RUNTIME_DATA_TYPE_END(NewbieSupportRewardPool)
RUNTIME_DATA_TYPE_INDEX(NewbieSupportRewardPool, Int32, RewardID)

RUNTIME_DATA_FILE_END