RUNTIME_DATA_FILE_BEGIN(overloadmastery.enc)

RUNTIME_DATA_TYPE_BEGIN(OverlordMasteryStart, "overloadmastery_system.Overloadmastery_start")
	RUNTIME_DATA_PROPERTY(Int32, RequiredLevel, "Needlevel")
	RUNTIME_DATA_PROPERTY(Int32, MasteryPointCount, "Getpoint")
RUNTIME_DATA_TYPE_END(OverlordMasteryStart)
RUNTIME_DATA_TYPE_INDEX_SINGLE(OverlordMasteryStart)

RUNTIME_DATA_TYPE_BEGIN(OverlordMasteryExp, "overloadmastery_system.overloadmastery_exp.Overloadmastery_exp")
	RUNTIME_DATA_PROPERTY(Int32, Level, "Overloadlevel")
	RUNTIME_DATA_PROPERTY(UInt64, RequiredExp, "Reqexp")
	RUNTIME_DATA_PROPERTY(UInt64, AccumulatedExp, "AReqexp")
	RUNTIME_DATA_PROPERTY(Int32, MasteryPointCount, "Getpoint")
RUNTIME_DATA_TYPE_END(OverlordMasteryExp)
RUNTIME_DATA_TYPE_INDEX(OverlordMasteryExp, Int32, Level)

RUNTIME_DATA_TYPE_BEGIN(OverlordMasteryBase, "overloadmastery_system.overloadmastery_base.mastery_base")
	RUNTIME_DATA_PROPERTY(Int32, MasteryCategory, "mastery_category")
	RUNTIME_DATA_PROPERTY(UInt64, MasteryIndex, "mastery_index")
	RUNTIME_DATA_PROPERTY(UInt64, MaxLevel, "Maxlv")
	RUNTIME_DATA_PROPERTY(Int32, RequiredLevel, "Reqlv")
	RUNTIME_DATA_PROPERTY(Int32, PreMasteryIndex, "Premastery_idx")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "Slot_num")
RUNTIME_DATA_TYPE_END(OverlordMasteryBase)
RUNTIME_DATA_TYPE_INDEX(OverlordMasteryBase, Int32, MasteryIndex)

RUNTIME_DATA_TYPE_BEGIN(OverlordMasteryValue, "overloadmastery_system.overloadmastery_value.mastery")
	RUNTIME_DATA_PROPERTY(Int32, Index, "index")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(OverlordMasteryValueLevel, "value")
		RUNTIME_DATA_PROPERTY(Int32, MasteryLevel, "overloadmastery_lv")
		RUNTIME_DATA_PROPERTY(Int32, RequiredMasteryPointCount, "usepoint")
		RUNTIME_DATA_PROPERTY(Int32, ForceEffect, "forcecode_num")
		RUNTIME_DATA_PROPERTY(Int32, ForceValue, "forcecode_value")
		RUNTIME_DATA_PROPERTY(Int32, ForceValueType, "value_type")
	RUNTIME_DATA_TYPE_END_CHILD(OverlordMasteryValueLevel)
RUNTIME_DATA_TYPE_END(OverlordMasteryValue)
RUNTIME_DATA_TYPE_INDEX(OverlordMasteryValue, Int32, Index)
RUNTIME_DATA_TYPE_INDEX_CHILD(OverlordMasteryValue, OverlordMasteryValueLevel, Int32, MasteryLevel)

RUNTIME_DATA_FILE_END
