RUNTIME_DATA_FILE_BEGIN(DIR_PATH(Service, PremiumServiceList.xml))

RUNTIME_DATA_TYPE_BEGIN(PremiumService, "PremiumServiceList.Service")
	RUNTIME_DATA_PROPERTY(Int32, ServiceID, "ID")
	RUNTIME_DATA_PROPERTY(Int32, Type, "Type")
	RUNTIME_DATA_PROPERTY(Int32, XP, "XP")
	RUNTIME_DATA_PROPERTY(Int32, SkillXP, "SkillXP")
	RUNTIME_DATA_PROPERTY(Int32, DropRate, "DropRate")
	RUNTIME_DATA_PROPERTY(Int32, AlzBombRate, "AlzBombRate")
	RUNTIME_DATA_PROPERTY(Int32, WarXP, "WarXP")
	RUNTIME_DATA_PROPERTY(Int32, PetXP, "PetXP")
	RUNTIME_DATA_PROPERTY(Int32, AXP, "AXP")
	RUNTIME_DATA_PROPERTY(Int32, TPointUp, "TPointUp")
	RUNTIME_DATA_PROPERTY(Int32, AlzDropRate, "AlzDropRate")
	RUNTIME_DATA_PROPERTY(Int32, BoxDropRate, "BoxDropRate")
	RUNTIME_DATA_PROPERTY(Int32, ForceWingXP, "ForceWingXP")
	RUNTIME_DATA_PROPERTY(Int32, Inventory1, "Inventory1")
	RUNTIME_DATA_PROPERTY(Int32, Inventory2, "Inventory2")
	RUNTIME_DATA_PROPERTY(Int32, Inventory3, "Inventory3")
	RUNTIME_DATA_PROPERTY(Int32, Inventory4, "Inventory4")
	RUNTIME_DATA_PROPERTY(Int32, Inventory5, "Inventory5")
	RUNTIME_DATA_PROPERTY(Int32, Inventory6, "Inventory6")
	RUNTIME_DATA_PROPERTY(Int32, ExtendPetSlot, "ExtendPetSlot")
	RUNTIME_DATA_PROPERTY(Int32, Warehouse, "Warehouse")
	RUNTIME_DATA_PROPERTY(Int32, SkillXPTDummy, "SkillXPTDummy")
	RUNTIME_DATA_PROPERTY(Int32, GPSWarpMask, "GPSWarpMask")
	RUNTIME_DATA_PROPERTY(Int32, UnlimitedWarp, "UnlimitedWarp")
	RUNTIME_DATA_PROPERTY(Int32, AuctionHouseItemBonusSlots, "AuctionHouseItemBonusSlots")
	RUNTIME_DATA_PROPERTY(Int32, AuctionHouseItemBonusQuantity, "AuctionHouseItemBonusQuantity")
	RUNTIME_DATA_PROPERTY(Int32, AuctionHouseItemBonusPeriod, "AuctionHouseItemBonusPeriod")
	RUNTIME_DATA_PROPERTY(Int32, AuctionHouseFeeExemption, "AuctionHouseFeeExemption")
	RUNTIME_DATA_PROPERTY(Int32, AbleToBuyPremiumItemFromShop, "AbleToBuyPremiumItemFromShop")
	RUNTIME_DATA_PROPERTY(Int32, RemoteShop, "RemoteShop")
	RUNTIME_DATA_PROPERTY(Int32, AbleToEnterPremiumDungeon, "AbleToEnterPremiumDungeon")
	RUNTIME_DATA_PROPERTY(Int32, PremiumDungeonReward, "PremiumDungeonReward")
	RUNTIME_DATA_PROPERTY(Int32, RemoteWarehouse, "RemoteWarehouse")
	RUNTIME_DATA_PROPERTY(Int32, CraftMasteryUp, "CraftMasteryUp")
	RUNTIME_DATA_PROPERTY(Int32, RequestAmityUp, "RequestAmityUp")
	RUNTIME_DATA_PROPERTY(Int32, RequestAmitySlots, "RequestAmitySlots")
	RUNTIME_DATA_PROPERTY(Int32, DungeonPlayTimeIncreased, "DungeonPlayTimeIncreased")
RUNTIME_DATA_TYPE_END(PremiumService)

RUNTIME_DATA_FILE_END