#ifndef RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX
#define RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX

enum {
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_MIN = 1,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_WA = 1,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_BL = 2,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_WI = 3,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_FA = 4,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_FS = 5,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_FB = 6,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_GL = 7,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_FG = 8,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_DM = 9,
	RUNTIME_DATA_CHARACTER_BATTLE_STYLE_INDEX_MAX = 9,
};

#endif

RUNTIME_DATA_FILE_BEGIN(rank.enc)

RUNTIME_DATA_TYPE_BEGIN(CharacterInit, "cabal.char_init.init", 16)
	RUNTIME_DATA_PROPERTY(Int32, Style, "style")
	RUNTIME_DATA_PROPERTY(Int32, WorldID, "world_id")
	RUNTIME_DATA_PROPERTY(Int32, X, "x")
	RUNTIME_DATA_PROPERTY(Int32, Y, "y")
	RUNTIME_DATA_PROPERTY(UInt32, Suit, "suit_1")
	RUNTIME_DATA_PROPERTY(UInt32, Glove, "glove_2")
	RUNTIME_DATA_PROPERTY(UInt32, Boot, "boot_3")
	RUNTIME_DATA_PROPERTY(UInt32, RightHand, "rhand_4")
	RUNTIME_DATA_PROPERTY(UInt32, LeftHand, "lhand_5")
	RUNTIME_DATA_PROPERTY(UInt32, DeltaHP, "delta_hp")
	RUNTIME_DATA_PROPERTY(UInt32, DeltaMP, "delta_mp")
	RUNTIME_DATA_PROPERTY(UInt32, HP, "hp")
	RUNTIME_DATA_PROPERTY(UInt32, MP, "mp")
RUNTIME_DATA_TYPE_END(CharacterInit)
RUNTIME_DATA_TYPE_INDEX(CharacterInit, UInt32, Style)

RUNTIME_DATA_TYPE_BEGIN(CharacterNewHP, "cabal.char_newhp.newhp", 16)
	RUNTIME_DATA_PROPERTY(Int32, Style, "bs")
	RUNTIME_DATA_PROPERTY(Int32, Delta, "bdelta")
RUNTIME_DATA_TYPE_END(CharacterNewHP)
RUNTIME_DATA_TYPE_INDEX(CharacterNewHP, UInt32, Style)

RUNTIME_DATA_TYPE_BEGIN(CharacterInitStat, "cabal.initstat.initstat", 16)
	RUNTIME_DATA_PROPERTY(Int32, Style, "id")
	RUNTIME_DATA_PROPERTY(Int32, Str, "str")
	RUNTIME_DATA_PROPERTY(Int32, Dex, "dex")
	RUNTIME_DATA_PROPERTY(Int32, Int, "int")
RUNTIME_DATA_TYPE_END(CharacterInitStat)
RUNTIME_DATA_TYPE_INDEX(CharacterInitStat, UInt32, Style)

RUNTIME_DATA_TYPE_BEGIN(CharacterMake, "cabal.char_make.make", 16)
	RUNTIME_DATA_PROPERTY(UInt32, Suit, "suit_1")
	RUNTIME_DATA_PROPERTY(UInt32, Glove, "glove_2")
	RUNTIME_DATA_PROPERTY(UInt32, Boot, "boot_3")
	RUNTIME_DATA_PROPERTY(UInt32, RightHand, "rhand_4")
	RUNTIME_DATA_PROPERTY(UInt32, LeftHand, "lhand_5")
	RUNTIME_DATA_PROPERTY(UInt32, Epaulet, "epaulet6")
RUNTIME_DATA_TYPE_END(CharacterMake)

RUNTIME_DATA_TYPE_BEGIN(CharacterRankUpCondition, "cabal.rankup.rankup_condition", 16)
	RUNTIME_DATA_PROPERTY(Int32, Rank, "rank")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(Condition, "condition", 1)
		RUNTIME_DATA_PROPERTY(Int32, WA, "twohand")
		RUNTIME_DATA_PROPERTY(Int32, BL, "dual")
		RUNTIME_DATA_PROPERTY(Int32, WI, "magic")
		RUNTIME_DATA_PROPERTY(Int32, FA, "magic_arrow")
		RUNTIME_DATA_PROPERTY(Int32, FS, "sword_shield")
		RUNTIME_DATA_PROPERTY(Int32, FB, "magic_sword")
		RUNTIME_DATA_PROPERTY(Int32, GL, "chakram")
		RUNTIME_DATA_PROPERTY(Int32, FG, "magic_gun")
		RUNTIME_DATA_PROPERTY(Int32, DM, "magic_skull")
	RUNTIME_DATA_TYPE_END_CHILD(Condition, 1)
RUNTIME_DATA_TYPE_END(CharacterRankUpCondition)

RUNTIME_DATA_TYPE_BEGIN(CharacterRankUpBonus, "cabal.rankup.rank_bonus", 16)
	RUNTIME_DATA_PROPERTY(UInt32, ReadyRank, "readyrank")
	RUNTIME_DATA_PROPERTY(UInt32, A, "anum")
	RUNTIME_DATA_PROPERTY(UInt32, B, "bnum")
	RUNTIME_DATA_PROPERTY(UInt32, Common, "commonnum")
	RUNTIME_DATA_PROPERTY(UInt32, Special, "specialnum")
	RUNTIME_DATA_PROPERTY(UInt32, Stat, "stat")
RUNTIME_DATA_TYPE_END(CharacterRankUpBonus)

RUNTIME_DATA_FILE_END
