RUNTIME_DATA_FILE_BEGIN(request.enc)

RUNTIME_DATA_TYPE_BEGIN(RequestCraftBase, "cabal_request_system.request_base")
	RUNTIME_DATA_PROPERTY(Int32, RequestLevel, "request_level")
	RUNTIME_DATA_PROPERTY(Int32, RequestExpMin, "request_exp_min")
	RUNTIME_DATA_PROPERTY(Int32, RequestExpMax, "request_exp_max")
RUNTIME_DATA_TYPE_END(RequestCraftBase)
RUNTIME_DATA_TYPE_INDEX(RequestCraftBase, Int32, RequestLevel)

RUNTIME_DATA_TYPE_BEGIN(RequestCraftRecipe, "cabal_request_system.request_recipe.recipe")
	RUNTIME_DATA_PROPERTY(Int32, RequestCode, "request_code")
	RUNTIME_DATA_PROPERTY(Int32, RequestLevel, "request_level")
	RUNTIME_DATA_PROPERTY(Int32, RegisterExp, "register_exp")
	RUNTIME_DATA_PROPERTY(Int32, RegisterCost, "register_cost")
	RUNTIME_DATA_PROPERTY_ARRAY(Int32, RegisterItem, "register_item", 2, ':')
	RUNTIME_DATA_PROPERTY_ARRAY(Int32, ResultItem, "result_item", 3, ':')
	RUNTIME_DATA_PROPERTY(Int32, ResultExp, "result_exp")
	RUNTIME_DATA_PROPERTY(Int32, Time, "time")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(RequestCraftRecipeMaterial, "material")
		RUNTIME_DATA_PROPERTY(UInt64, ItemIndex, "request_material_itemindex")
		RUNTIME_DATA_PROPERTY(UInt64, ItemOption, "request_material_itemoption")
		RUNTIME_DATA_PROPERTY(Int32, ItemCount, "craft_material_itemcount")
		RUNTIME_DATA_PROPERTY(Int32, ItemBind, "craft_material_itembind")
		RUNTIME_DATA_PROPERTY(Int32, ItemUpgrade, "craft_material_upgrade")
		RUNTIME_DATA_PROPERTY(Int32, ItemUsagePeriod, "craft_material_useperiod")
	RUNTIME_DATA_TYPE_END_CHILD(RequestCraftRecipeMaterial)
RUNTIME_DATA_TYPE_END(RequestCraftRecipe)
RUNTIME_DATA_TYPE_INDEX(RequestCraftRecipe, Int32, RequestCode)

RUNTIME_DATA_FILE_END