#ifndef RUNTIME_DATA_DUMMY_SKILL_CASE
#define RUNTIME_DATA_DUMMY_SKILL_CASE

enum {
	RUNTIME_DATA_DUMMY_SKILL_CASE_BATTLE_MODE_ENCHANT,
	RUNTIME_DATA_DUMMY_SKILL_CASE_BATTLE_MODE_UNKNOWN,
	RUNTIME_DATA_DUMMY_SKILL_CASE_COMBO_MODE,
};

#endif

RUNTIME_DATA_FILE_BEGIN(DummySkill.xml)

RUNTIME_DATA_TYPE_BEGIN(DummySkill, "DummySkillList.DummySkill", 16)
	RUNTIME_DATA_PROPERTY(Int32, Index, "Index")
	RUNTIME_DATA_PROPERTY(Int32, Case, "Case")
	RUNTIME_DATA_PROPERTY(Int32, Property, "Property")
	RUNTIME_DATA_PROPERTY(Int32, SkillIndex, "SkillIndex")
RUNTIME_DATA_TYPE_END(DummySkill)

RUNTIME_DATA_FILE_END
