RUNTIME_DATA_FILE_BEGIN(Skill_Enhanced.enc)

RUNTIME_DATA_TYPE_BEGIN(TranscendenceSkill, "Enhanced_Skill_Sys.Enhanced_Skill_List.Enhanced_Skill")
	RUNTIME_DATA_PROPERTY(Int32, BattleStyleIndex, "BS")
	RUNTIME_DATA_PROPERTY(Int32, SkillIndex, "Skill_id")
	RUNTIME_DATA_PROPERTY(Int32, OverlordLevel, "OLV")
	RUNTIME_DATA_PROPERTY(Int32, Rank, "Rank")
	RUNTIME_DATA_PROPERTY(Int32, TranscendenceIndex, "Enhanced_id")
RUNTIME_DATA_TYPE_END(TranscendenceSkill)

RUNTIME_DATA_TYPE_BEGIN(TranscendenceValue, "Enhanced_Skill_Sys.Enhanced_ID_List.Enhanced")
	RUNTIME_DATA_PROPERTY(Int32, Index, "ID")
	RUNTIME_DATA_PROPERTY(Int32, ForceEffectIndex, "ForceCode_id")
	RUNTIME_DATA_PROPERTY(Int32, ForceValue, "Value")
	RUNTIME_DATA_PROPERTY(Int32, ForceValueType, "value_type")
RUNTIME_DATA_TYPE_END(TranscendenceValue)

RUNTIME_DATA_TYPE_BEGIN(TranscendencePoints, "Enhanced_Skill_Sys.Skill_Point.SP")
	RUNTIME_DATA_PROPERTY(Int32, OverlordLevel, "OLV")
	RUNTIME_DATA_PROPERTY(Int32, Points, "Point")
RUNTIME_DATA_TYPE_END(TranscendencePoints)
RUNTIME_DATA_TYPE_INDEX(TranscendencePoints, Int32, OverlordLevel)

RUNTIME_DATA_TYPE_BEGIN(TranscendenceSlot, "Enhanced_Skill_Sys.Slot_List.Slot")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "Slot_id")
	RUNTIME_DATA_PROPERTY(Int32, OpenOverlordLevel, "Open_OLv")
	RUNTIME_DATA_PROPERTY(Int32, PreviousSlotIndex, "Preceding_Slot_id")
	RUNTIME_DATA_PROPERTY(Int32, PreviourSlotLevel, "Preceding_Slot_Lv")
	RUNTIME_DATA_PROPERTY(Int32, SlotType, "Slot_type")
	RUNTIME_DATA_PROPERTY(Int32, MaxLevel, "Maxlv")
	RUNTIME_DATA_PROPERTY(Int32, MaterialPointType, "Cost_Point_Type")
	RUNTIME_DATA_PROPERTY(Int32, MaterialPointValue, "Cost_Point_Value")
	RUNTIME_DATA_PROPERTY(UInt64, MaterialItemID1, "Cost_Item_id1")
	RUNTIME_DATA_PROPERTY(Int32, MaterialItemCount1, "Count_1")
	RUNTIME_DATA_PROPERTY(UInt64, MaterialItemID2, "Cost_Item_id2")
	RUNTIME_DATA_PROPERTY(Int32, MaterialItemCount2, "Count_2")
	RUNTIME_DATA_PROPERTY(Int32, TrainCost, "TrainCost")
RUNTIME_DATA_TYPE_END(TranscendenceSlot)

RUNTIME_DATA_TYPE_BEGIN(TranscendencePerk, "Enhanced_Skill_Sys.Perk_List.Perk")
	RUNTIME_DATA_PROPERTY(Int32, PerkIndex, "Perk_id")
	RUNTIME_DATA_PROPERTY(Int32, BattleStyleIndex, "BS")
	RUNTIME_DATA_PROPERTY(Int32, SlotIndex, "Slot_id")
RUNTIME_DATA_TYPE_END(TranscendencePerk)

RUNTIME_DATA_TYPE_BEGIN(TranscendenceSkillSet, "Enhanced_Skill_Sys.SkillSet_List.SkillSet")
	RUNTIME_DATA_PROPERTY(Int32, PerkIndex, "Perk_id")
	RUNTIME_DATA_PROPERTY(Int32, SkillIndex, "Skill_id")
	RUNTIME_DATA_PROPERTY(Int32, ForceEffectIndex, "ForceCode_id")
	RUNTIME_DATA_PROPERTY(Int32, ForceValue, "Value")
	RUNTIME_DATA_PROPERTY(Int32, ForceValueType, "value_type")
RUNTIME_DATA_TYPE_END(TranscendenceSkillSet)

RUNTIME_DATA_FILE_END