RUNTIME_DATA_FILE_BEGIN(stellar.enc)

RUNTIME_DATA_TYPE_BEGIN(StellarGroup, "stellar_ability.stellar_main.stellar_info")
	RUNTIME_DATA_PROPERTY(UInt32, GroupID, "group_id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(StellarLine, "detail")
		RUNTIME_DATA_PROPERTY(UInt32, LineID, "line_no")
		RUNTIME_DATA_TYPE_BEGIN_CHILD(StellarLineGrade, "group")
			RUNTIME_DATA_PROPERTY(UInt32, Grade, "grade")
			RUNTIME_DATA_PROPERTY(UInt32, ForceCodePer, "forcecode_per")
			RUNTIME_DATA_PROPERTY(UInt32, ItemID, "Itemkind")
			RUNTIME_DATA_PROPERTY(UInt32, ItemCount, "itemcount")
			RUNTIME_DATA_PROPERTY(UInt32, MinGrade, "mingrade")
			RUNTIME_DATA_PROPERTY(UInt32, MaxGrade, "maxgrade")
		RUNTIME_DATA_TYPE_END_CHILD(StellarLineGrade)
	RUNTIME_DATA_TYPE_END_CHILD(StellarLine)
RUNTIME_DATA_TYPE_END(StellarGroup)
RUNTIME_DATA_TYPE_INDEX(StellarGroup, UInt32, GroupID)
RUNTIME_DATA_TYPE_INDEX_CHILD(StellarGroup, StellarLine, UInt32, LineID)
RUNTIME_DATA_TYPE_INDEX_CHILD(StellarLine, StellarLineGrade, UInt32, Grade)

RUNTIME_DATA_TYPE_BEGIN(StellarTransformationGroup, "stellar_ability.fixed_grade.fixed_info")
	RUNTIME_DATA_PROPERTY(UInt32, GroupID, "group_id")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(StellarLineTransformation, "detail")
		RUNTIME_DATA_PROPERTY(UInt32, LineID, "line_no")
		RUNTIME_DATA_TYPE_BEGIN_CHILD(StellarLineTransformationGrade, "group")
			RUNTIME_DATA_PROPERTY(UInt32, Grade, "grade")
			RUNTIME_DATA_PROPERTY(UInt32, ItemID, "Itemkind")
			RUNTIME_DATA_PROPERTY(UInt32, ItemCount, "itemcount")
		RUNTIME_DATA_TYPE_END_CHILD(StellarLineTransformationGrade)
	RUNTIME_DATA_TYPE_END_CHILD(StellarLineTransformation)
RUNTIME_DATA_TYPE_END(StellarTransformationGroup)
RUNTIME_DATA_TYPE_INDEX(StellarTransformationGroup, UInt32, GroupID)
RUNTIME_DATA_TYPE_INDEX_CHILD(StellarTransformationGroup, StellarLineTransformation, UInt32, LineID)
RUNTIME_DATA_TYPE_INDEX_CHILD(StellarLineTransformation, StellarLineTransformationGrade, UInt32, Grade)

RUNTIME_DATA_FILE_END

RUNTIME_DATA_FILE_BEGIN(DIR_PATH(Character, StellarMastery.xml))

RUNTIME_DATA_TYPE_BEGIN(StellarForcePool, "StellarMastery.ForceEffectPoolGroup.Pool")
	RUNTIME_DATA_PROPERTY(Int32, PoolID, "ID")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(StellarForceEffect, "ForceEffect")
		RUNTIME_DATA_PROPERTY(UInt32, Chance, "Rate")
		RUNTIME_DATA_PROPERTY(UInt32, ForceEffectID, "ForceIndex")
		RUNTIME_DATA_PROPERTY(UInt32, Value, "Value")
		RUNTIME_DATA_PROPERTY(UInt32, ValueType, "ValueType")
	RUNTIME_DATA_TYPE_END_CHILD(StellarForceEffect)
RUNTIME_DATA_TYPE_END(StellarForcePool)
RUNTIME_DATA_TYPE_INDEX(StellarForcePool, Int32, PoolID)
RUNTIME_DATA_TYPE_INDEX_CHILD(StellarForcePool, StellarForceEffect, UInt32, ForceEffectID)

RUNTIME_DATA_TYPE_BEGIN(StellarForceValuePool, "StellarMastery.ForceValuePoolGroup.Pool")
	RUNTIME_DATA_PROPERTY(Int32, PoolID, "ID")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(StellarForceValue, "ForceValue")
		RUNTIME_DATA_PROPERTY(UInt32, Chance, "Rate")
		RUNTIME_DATA_PROPERTY(UInt32, StellarForcePoolID, "PoolIndex")
	RUNTIME_DATA_TYPE_END_CHILD(StellarForceValue)
RUNTIME_DATA_TYPE_END(StellarForceValuePool)
RUNTIME_DATA_TYPE_INDEX(StellarForceValuePool, Int32, PoolID)
RUNTIME_DATA_TYPE_INDEX_CHILD(StellarForceValuePool, StellarForceValue, UInt32, StellarForcePoolID)

RUNTIME_DATA_TYPE_BEGIN(StellarLinkPool, "StellarMastery.ForceLinkPoolGroup.Pool")
	RUNTIME_DATA_PROPERTY(UInt32, PoolID, "ID")
	RUNTIME_DATA_TYPE_BEGIN_CHILD(StellarLink, "ForceLink")
		RUNTIME_DATA_PROPERTY(UInt32, Grade, "Grade")
		RUNTIME_DATA_PROPERTY(UInt32, Chance, "Rate")
	RUNTIME_DATA_TYPE_END_CHILD(StellarLink)
RUNTIME_DATA_TYPE_END(StellarLinkPool)
RUNTIME_DATA_TYPE_INDEX(StellarLinkPool, UInt32, PoolID)
RUNTIME_DATA_TYPE_INDEX_CHILD(StellarLinkPool, StellarLink, UInt32, Grade)

RUNTIME_DATA_FILE_END
