RUNTIME_DATA_FILE_BEGIN(Warp.enc)

RUNTIME_DATA_TYPE_BEGIN(WarpPoint, "Warp.warp_point.warp_index")
	RUNTIME_DATA_PROPERTY(Int32, X, "x")
	RUNTIME_DATA_PROPERTY(Int32, Y, "y")
	RUNTIME_DATA_PROPERTY(Int32, Nation1X, "nation1x")
	RUNTIME_DATA_PROPERTY(Int32, Nation1Y, "nation1y")
	RUNTIME_DATA_PROPERTY(Int32, Nation2X, "nation2x")
	RUNTIME_DATA_PROPERTY(Int32, Nation2Y, "nation2y")
	RUNTIME_DATA_PROPERTY(Int32, Nation3X, "nation3x")
	RUNTIME_DATA_PROPERTY(Int32, Nation3Y, "nation3y")
	RUNTIME_DATA_PROPERTY(Int32, WCode, "w_code")
	RUNTIME_DATA_PROPERTY(Int32, Fee, "Fee")
	RUNTIME_DATA_PROPERTY(Int32, WorldIndex, "WorldIdx")
	RUNTIME_DATA_PROPERTY(Int32, Level, "level")
RUNTIME_DATA_TYPE_END(WarpPoint)

RUNTIME_DATA_FILE_END