#include "ClientProtocol.h"
#include "ClientProcedures.h"

SERVER_PROCEDURE_BINDING(NFY_ERROR_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_CHARACTERS_WORLD) {}

SERVER_PROCEDURE_BINDING(CREATE_CHARACTER_WORLD) {}

SERVER_PROCEDURE_BINDING(DELETE_CHARACTER_WORLD) {}

SERVER_PROCEDURE_BINDING(CONNECT_WORLD) {
	KeychainSeed(&Connection->Keychain, Packet->XorKey, Packet->XorKeyIndex);
}

SERVER_PROCEDURE_BINDING(VERIFY_LINKS_WORLD) {}

SERVER_PROCEDURE_BINDING(INITIALIZE_WORLD) {}

SERVER_PROCEDURE_BINDING(DEINITIALIZE_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_WAREHOUSE_WORLD) {}

SERVER_PROCEDURE_BINDING(SET_QUICKSLOT_WORLD) {}

SERVER_PROCEDURE_BINDING(SWAP_QUICKSLOT_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_SERVER_TIME_WORLD) {}

SERVER_PROCEDURE_BINDING(LOOT_INVENTORY_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(LOOT_CURRENCY_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(BUY_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(SELL_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(RECOVER_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_ITEM_RECOVERY_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(WAREHOUSE_CURRENCY_DEPOSIT_WORLD) {}

SERVER_PROCEDURE_BINDING(SKILL_TO_MOB_WORLD) {}

SERVER_PROCEDURE_BINDING(SKILL_TO_CHARACTER_WORLD) {}

SERVER_PROCEDURE_BINDING(ATTACK_TO_MOB_WORLD) {}

SERVER_PROCEDURE_BINDING(ATTACK_TO_CHARACTER_WORLD) {}

SERVER_PROCEDURE_BINDING(CHARACTERS_SPAWN_WORLD) {}

SERVER_PROCEDURE_BINDING(CHARACTERS_DESPAWN_WORLD) {}

SERVER_PROCEDURE_BINDING(MOBS_SPAWN_WORLD) {}

SERVER_PROCEDURE_BINDING(MOBS_DESPAWN_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_SPAWN_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_DESPAWN_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_EQUIP_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UNEQUIP_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(MOVEMENT_BEGIN_WORLD) {}

SERVER_PROCEDURE_BINDING(MOVEMENT_END_WORLD) {}

SERVER_PROCEDURE_BINDING(MOVEMENT_CHANGE_WORLD) {}

SERVER_PROCEDURE_BINDING(MOB_MOVEMENT_BEGIN_WORLD) {}

SERVER_PROCEDURE_BINDING(MOB_MOVEMENT_END_WORLD) {}

SERVER_PROCEDURE_BINDING(MOB_CHASE_BEGIN_WORLD) {}

SERVER_PROCEDURE_BINDING(MOB_CHASE_END_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_SKILL_TO_MOB_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_SKILL_TO_CHARACTER_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_ATTACK_TO_MOB_WORLD) {}

SERVER_PROCEDURE_BINDING(WARP_WORLD) {}

SERVER_PROCEDURE_BINDING(BATTLE_RANK_UP_WORLD) {}

SERVER_PROCEDURE_BINDING(ADD_FORCE_SLOT_OPTION_WORLD) {}

SERVER_PROCEDURE_BINDING(QUEST_BEGIN_WORLD) {}

SERVER_PROCEDURE_BINDING(QUEST_CLEAR_WORLD) {}

SERVER_PROCEDURE_BINDING(QUEST_CANCEL_WORLD) {}

SERVER_PROCEDURE_BINDING(USE_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_CHARACTER_DATA_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_CHARACTER_EVENT_WORLD) {}

SERVER_PROCEDURE_BINDING(QUEST_DUNGEON_START_WORLD) {}

SERVER_PROCEDURE_BINDING(QUEST_DUNGEON_END_WORLD) {}

SERVER_PROCEDURE_BINDING(QUEST_DUNGEON_GATE_OPEN_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_QUEST_DUNGEON_END_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_QUEST_DUNGEON_CLEAR_MOBS_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_QUEST_DUNGEON_SPAWN_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UNKNOWN_302_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_QUEST_DUNGEON_PATTERN_PART_COMPLETED_WORLD) {}

SERVER_PROCEDURE_BINDING(SKILL_TO_ACTION_WORLD) {}

SERVER_PROCEDURE_BINDING(QUEST_ACTION_WORLD) {}

SERVER_PROCEDURE_BINDING(ATTACK_BOSS_MOB_WORLD) {}

SERVER_PROCEDURE_BINDING(CHANGE_STYLE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_CHANGE_STYLE_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_PREMIUM_SERVICE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PREMIUM_SERVICE_WORLD) {}

SERVER_PROCEDURE_BINDING(REPUTATION_CHANGE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_REPUTATION_CHANGE_WORLD) {}

SERVER_PROCEDURE_BINDING(SELECT_TARGET_CHARACTER_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_QUEST_BEGIN_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_QUEST_BEGIN_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_QUEST_CLOSE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_QUEST_CLOSE_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_QUEST_ACTION_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_QUEST_ACTION_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_QUEST_LOOT_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_QUEST_LOOT_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_QUEST_MISSION_MOB_KILL_WORLD) {}

SERVER_PROCEDURE_BINDING(CHANGE_DIRECTION_WORLD) {}

SERVER_PROCEDURE_BINDING(KEY_MOVEMENT_BEGIN_WORLD) {}

SERVER_PROCEDURE_BINDING(KEY_MOVEMENT_END_WORLD) {}

SERVER_PROCEDURE_BINDING(KEY_MOVEMENT_CHANGE_WORLD) {}

SERVER_PROCEDURE_BINDING(EXTRACT_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_MOB_ATTACK_AOE_WORLD) {}

SERVER_PROCEDURE_BINDING(UNKNOWN_428_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_SERVER_ENVIRONMENT_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PC_BANG_ALERT_WORLD) {}

SERVER_PROCEDURE_BINDING(CHECK_DUNGEON_PLAYTIME_WORLD) {}

SERVER_PROCEDURE_BINDING(PUSH_EQUIPMENT_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(UPDATE_SKILL_STATUS_WORLD) {}

SERVER_PROCEDURE_BINDING(VERIFY_CREDENTIALS_WORLD) {}

SERVER_PROCEDURE_BINDING(UPGRADE_ITEM_LEVEL_WORLD) {}

SERVER_PROCEDURE_BINDING(UNKNOWN_985_WORLD) {}

SERVER_PROCEDURE_BINDING(PREMIUM_BENEFIT_INFO_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_EVENT_INFO_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_EVENT_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(EVENT_ACTION_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_EVENT_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(CREATE_SUBPASSWORD_WORLD) {}

SERVER_PROCEDURE_BINDING(CHECK_SUBPASSWORD_WORLD) {}

SERVER_PROCEDURE_BINDING(VERIFY_SUBPASSWORD_WORLD) {}

SERVER_PROCEDURE_BINDING(VERIFY_DELETE_SUBPASSWORD_WORLD) {}
 
SERVER_PROCEDURE_BINDING(DELETE_SUBPASSWORD_WORLD) {}

SERVER_PROCEDURE_BINDING(ADD_PASSIVE_ABILITY_WORLD) {}

SERVER_PROCEDURE_BINDING(UPGRADE_PASSIVE_ABILITY_WORLD) {}

SERVER_PROCEDURE_BINDING(REMOVE_PASSIVE_ABILITY_WORLD) {}

SERVER_PROCEDURE_BINDING(BUY_SKILLBOOK_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_QUEST_MOB_KILL_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_INVITE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_INVITE_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_INVITE_CONFIRM_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_INVITE_TIMEOUT_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_INFO_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_INVITE_CANCEL_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_INVITE_CANCEL_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_LEAVE_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_DISBAND_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_EXPEL_MEMBER_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_EXPEL_MEMBER_WORLD) {}

SERVER_PROCEDURE_BINDING(PARTY_CHANGE_LEADER_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_CHANGE_LEADER_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_INVITE_RULE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_UPDATE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_PICK_UP_CURRENCY_WORLD) {}

SERVER_PROCEDURE_BINDING(ENTER_DUNGEON_GATE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_PARTY_INIT_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_MESSAGE_BROADCAST_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_SERVER_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_SERVER_STATUS_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_SPECIAL_EVENT_CHARACTER_WORLD) {}

SERVER_PROCEDURE_BINDING(VERIFY_CREDENTIALS_SUBPASSWORD_WORLD) {}

SERVER_PROCEDURE_BINDING(MOVE_INVENTORY_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(SWAP_INVENTORY_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(MOVE_INVENTORY_ITEM_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(CONVERT_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(UNKNOWN_2173_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_SHOP_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_SHOP_DATA_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_CASH_BALANCE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UNKNOWN_2248_WORLD) {}

SERVER_PROCEDURE_BINDING(REQUEST_CRAFT_REGISTER_WORLD) {}

SERVER_PROCEDURE_BINDING(REQUEST_CRAFT_START_WORLD) {}

SERVER_PROCEDURE_BINDING(REQUEST_CRAFT_END_WORLD) {}

SERVER_PROCEDURE_BINDING(REQUEST_CRAFT_UPDATE_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_UNKNOWN_USER_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_USER_MESSAGE_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_UNKNOWN_SHOP_ITEM_PRICE_WORLD) {}

SERVER_PROCEDURE_BINDING(UPGRADE_EXTREME_LEVEL_WORLD) {}

SERVER_PROCEDURE_BINDING(UPGRADE_EXTREME_REPAIR_WORLD) {}

SERVER_PROCEDURE_BINDING(TAKE_NEWBIE_REWARD_WORLD) {}

SERVER_PROCEDURE_BINDING(MERGE_INVENTORY_WORLD) {}

SERVER_PROCEDURE_BINDING(UPDATE_UPGRADE_POINTS_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UNKNOWN_2518_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_DUNGEON_REWARD_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_DUNGEON_COMPLETE_INFO_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_UNKNOWN_2522_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UNKNOWN_2528_WORLD) {}

SERVER_PROCEDURE_BINDING(UNKNOWN_2559_WORLD) {}

SERVER_PROCEDURE_BINDING(UNKNOWN_2566_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_UNKNOWN_2571_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_CASHSHOP_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(CHANGE_CHARACTER_SKILL_LEVEL_WORLD) {}

SERVER_PROCEDURE_BINDING(ADD_CHARACTER_STATS_WORLD) {}

SERVER_PROCEDURE_BINDING(REMOVE_CHARACTER_STATS_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UNKNOWN_2756_WORLD) {}

SERVER_PROCEDURE_BINDING(ADD_OVERLORD_MASTERY_SLOT_WORLD) {}

SERVER_PROCEDURE_BINDING(EXTREME_UPGRADE_SEAL_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_FORCE_WING_GRADE_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_FORCE_WING_UPDATE_WORLD) {}

SERVER_PROCEDURE_BINDING(FORCE_WING_LEVEL_UP_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_FORCE_WING_EXP_WORLD) {}

SERVER_PROCEDURE_BINDING(SET_FORCEWING_PRESET_SLOT_WORLD) {}

SERVER_PROCEDURE_BINDING(ADD_FORCEWING_TRAINING_LEVEL_WORLD) {}

SERVER_PROCEDURE_BINDING(SET_ACTIVE_FORCEWING_PRESET_WORLD) {}

SERVER_PROCEDURE_BINDING(OPEN_GIFTBOX_WORLD) {}

SERVER_PROCEDURE_BINDING(SORT_INVENTORY_WORLD) {}

SERVER_PROCEDURE_BINDING(SORT_WAREHOUSE_WORLD) {}

SERVER_PROCEDURE_BINDING(OPEN_GIFTBOX_UNKNOWN_WORLD) {}

SERVER_PROCEDURE_BINDING(UNKNOWN_2828_WORLD) {}

SERVER_PROCEDURE_BINDING(REGISTER_COLLECTION_ITEM_WORLD) {}

SERVER_PROCEDURE_BINDING(RECEIVE_COLLECTION_REWARD_WORLD) {}

SERVER_PROCEDURE_BINDING(FORCE_WING_GRADE_UP_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UPDATE_TRANSCENDENCE_POINTS_WORLD) {}

SERVER_PROCEDURE_BINDING(ROLL_FORCEWING_ARRIVAL_SKILL_WORLD) {}

SERVER_PROCEDURE_BINDING(CHANGE_FORCEWING_ARRIVAL_SKILL_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_EVENT_PASS_REWARD_LIST_WORLD) {}

SERVER_PROCEDURE_BINDING(GET_EVENT_PASS_SEASON_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_EVENT_PASS_PROGRESS_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_EVENT_PASS_RESUME_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UNKNOWN_3016_WORLD) {}

SERVER_PROCEDURE_BINDING(NFY_UNKNOWN_5305_WORLD) {}

SERVER_PROCEDURE_BINDING(UNKNOWN_5383_WORLD) {}
