CREATE TABLE Accounts (
    AccountID INT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(16) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    EmailVerified BOOLEAN NOT NULL DEFAULT FALSE,
    PasswordHash VARBINARY(128) NOT NULL,
    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    DeletedAt BIGINT UNSIGNED DEFAULT NULL,

    PRIMARY KEY (AccountID),
    UNIQUE (Username),
    UNIQUE (Email)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
