CREATE TABLE Sessions (
    AccountID INT NOT NULL,
    Online BOOLEAN NOT NULL DEFAULT FALSE,
    AuthKey VARCHAR(32) NOT NULL DEFAULT '',
    AddressIP VARCHAR(45) NOT NULL DEFAULT '0.0.0.0',
    SessionAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),

    PRIMARY KEY (AccountID)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
