CREATE TABLE Characters (
    AccountID INT NOT NULL,
    ServerID TINYINT UNSIGNED NOT NULL,
    CharacterCount TINYINT UNSIGNED NOT NULL,    
    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(CURRENT_TIMESTAMP),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(CURRENT_TIMESTAMP),

    PRIMARY KEY (AccountID, ServerID)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
