CREATE TABLE Accounts (
    AccountID INT NOT NULL,
    AddressIP VARCHAR(45) NOT NULL DEFAULT '0.0.0.0',
    CharacterSlotID INT NOT NULL DEFAULT 0,
    CharacterSlotOrder BIGINT UNSIGNED NOT NULL DEFAULT 0x0123456789ABCDEF,
    CharacterSlotOpenMask INT UNSIGNED NOT NULL DEFAULT 0x3F,
    ForceGems INT NOT NULL DEFAULT 0,
    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),

    PRIMARY KEY (AccountID)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
