CREATE TABLE Subpasswords (
    AccountID INT NOT NULL,
    EquipmentPassword VARCHAR(11) DEFAULT NULL,
    EquipmentQuestion INT UNSIGNED NOT NULL DEFAULT 0,
    EquipmentAnswer VARCHAR(17) DEFAULT NULL,
    EquipmentLocked BOOLEAN DEFAULT FALSE,
    WarehousePassword VARCHAR(11) DEFAULT NULL,
    WarehouseQuestion INT UNSIGNED NOT NULL DEFAULT 0,
    WarehouseAnswer VARCHAR(17) DEFAULT NULL,
    WarehouseLocked BOOLEAN DEFAULT FALSE,
    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),

    PRIMARY KEY (AccountID)
) ENGINE = INNODB DEFAULT CHARSET = utf8;