CREATE TABLE Services (
    ID INT NOT NULL AUTO_INCREMENT,
    AccountID INT NOT NULL,
    ServiceType INT UNSIGNED NOT NULL,
    StartedAt BIGINT UNSIGNED NOT NULL,
    ExpiredAt BIGINT UNSIGNED NOT NULL,
    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),

    PRIMARY KEY (ID)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
