CREATE TABLE BattleMode (
    CharacterID INT NOT NULL, 
    BattleModeDuration INT UNSIGNED NOT NULL DEFAULT 0,
    BattleModeIndex TINYINT UNSIGNED NOT NULL DEFAULT 0,
    BattleModeUnknown1 TINYINT UNSIGNED NOT NULL DEFAULT 0,
    BattleModeStyleRank TINYINT UNSIGNED NOT NULL DEFAULT 0,
    AuraModeIndex TINYINT UNSIGNED NOT NULL DEFAULT 0,
    AuraModeUnknown1 TINYINT UNSIGNED NOT NULL DEFAULT 0,
    AuraModeStyleRank TINYINT UNSIGNED NOT NULL DEFAULT 0,
    AuraModeDuration INT UNSIGNED NOT NULL DEFAULT 0,
    VehicleState INT NOT NULL DEFAULT -1,

    PRIMARY KEY (CharacterID),

    CONSTRAINT FK_Character_BattleMode FOREIGN KEY (CharacterID)
        REFERENCES Characters(CharacterID)
        ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8;
