CREATE TABLE Buff (
    CharacterID INT NOT NULL, 
    SkillBuffCount TINYINT UNSIGNED NOT NULL DEFAULT 0,
    PotionBuffCount TINYINT UNSIGNED NOT NULL DEFAULT 0,
    GmBuffCount TINYINT UNSIGNED NOT NULL DEFAULT 0,
    UnknownBuffCount1 TINYINT UNSIGNED NOT NULL DEFAULT 0,
    UnknownBuffCount2 TINYINT UNSIGNED NOT NULL DEFAULT 0,
    ForceWingBuffCount TINYINT UNSIGNED NOT NULL DEFAULT 0,
    FirePlaceBuffCount TINYINT UNSIGNED NOT NULL DEFAULT 0,
    SlotData BLOB NOT NULL, 

    PRIMARY KEY (CharacterID),

    CONSTRAINT FK_Character_Buff FOREIGN KEY (CharacterID)
        REFERENCES Characters(CharacterID)
        ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8;
