CREATE PROCEDURE SyncCharacter (
    IN InCharacterID INT,
    IN InPKState SMALLINT UNSIGNED,
    IN InLevel TINYINT UNSIGNED,
    IN InExp BIGINT UNSIGNED,
    IN InHonorPoint BIGINT,
    IN InHonorExp BIGINT,
    IN InHP BIGINT,
    IN InMP BIGINT,
    IN InSP BIGINT,
    IN InBP BIGINT,
    IN InRage BIGINT,
    IN InDP BIGINT,
    IN InDPDuration BIGINT UNSIGNED,
    IN InSkillRank TINYINT UNSIGNED,
    IN InSkillLevel SMALLINT UNSIGNED,
    IN InSkillExp BIGINT UNSIGNED,
    IN InSkillPoint SMALLINT UNSIGNED,
    IN InStatSTR SMALLINT UNSIGNED,
    IN InStatDEX SMALLINT UNSIGNED,
    IN InStatINT SMALLINT UNSIGNED,
    IN InStatPNT SMALLINT UNSIGNED,
    IN InCurrency BIGINT UNSIGNED,
    IN InWorldIndex TINYINT UNSIGNED,
    IN InX SMALLINT UNSIGNED,
    IN InY SMALLINT UNSIGNED,
    IN InDungeonIndex INT
)
BEGIN
    UPDATE Characters
    SET
        PKState = InPKState,
        Level = InLevel,
        Exp = InExp,
        HonorPoint = InHonorPoint,
        HonorExp = InHonorExp,
        HP = InHP,
        MP = InMP,
        SP = InSP,
        BP = InBP,
        Rage = InRage,
        DP = InDP,
        DPDuration = InDPDuration,
        SkillRank = InSkillRank,
        SkillLevel = InSkillLevel,
        SkillExp = InSkillExp,
        SkillPoint = InSkillPoint,
        StatSTR = InStatSTR,
        StatDEX = InStatDEX,
        StatINT = InStatINT,
        StatPNT = InStatPNT,
        Currency = InCurrency,
        WorldIndex = InWorldIndex,
        X = InX,
        Y = InY,
        DungeonIndex = InDungeonIndex,
        UpdatedAt = UNIX_TIMESTAMP()
    WHERE CharacterID = InCharacterID;
END;
