CREATE TABLE AuctionItems (
    AccountID INT NOT NULL,
    SlotIndex TINYINT NOT NULL,
    ItemID BIGINT UNSIGNED NOT NULL,
    ItemOptions BIGINT UNSIGNED NOT NULL,
    ItemDuration INT UNSIGNED NOT NULL,
    ItemPrice BIGINT UNSIGNED NOT NULL,
    ItemCount INT NOT NULL,
    SoldItemCount INT NOT NULL DEFAULT 0,
    Category1 SMALLINT NOT NULL,
    Category2 SMALLINT NOT NULL,
    Category3 SMALLINT NOT NULL,
    Category4 SMALLINT NOT NULL,
    Category5 SMALLINT NOT NULL,
    CharacterID INT NOT NULL,
    CharacterName VARCHAR(50) NOT NULL,

    ExpiresAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),

    UNIQUE (AccountID, SlotIndex)
) ENGINE = INNODB DEFAULT CHARSET = utf8;