CREATE TABLE Guilds (
    ID INT NOT NULL AUTO_INCREMENT,
    OwnerID INT NOT NULL,
    Name VARCHAR(40) NOT NULL,
    Message VARCHAR(200) NOT NULL,
    Level INT NOT NULL,

    ExpiresAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),

    PRIMARY KEY (ID),
    UNIQUE (OwnerID)
) ENGINE = INNODB DEFAULT CHARSET = utf8;