CREATE TABLE CashInventory (
    AccountID INT NOT NULL,
    TransactionID INT NOT NULL AUTO_INCREMENT,
    ItemID BIGINT UNSIGNED NOT NULL,
    ItemOptions BIGINT UNSIGNED NOT NULL,
    ItemDurationIndex TINYINT UNSIGNED NOT NULL,

    CreatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    UpdatedAt BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    DeletedAt BIGINT UNSIGNED DEFAULT NULL,

    PRIMARY KEY (TransactionID)
) ENGINE = INNODB DEFAULT CHARSET = utf8;