#pragma once

#include <CoreLib/CoreLib.h>

EXTERN_C_BEGIN

#define CLIENT_RSA_PAYLOAD_LENGTH 162

#define MAX_SERVER_GROUP_COUNT 8
#define MAX_SERVER_GROUP_NODE_COUNT 32
#define MAX_HOSTNAME_LENGTH 64
#define MAX_USERNAME_LENGTH 16
#define MAX_PASSWORD_LENGTH 16
#define MAX_PASSWORD_SALT_LENGTH 64
#define MAX_PASSWORD_HASH_LENGTH 64
#define MAX_EMAIL_LENGTH 256
#define MAX_SERVER_COUNT 128
#define MAX_SESSIONKEY_LENGTH 32
#define MAX_DESCRIPTION_LENGTH 256
#define MAX_CREDENTIALS_LENGTH 32

#define MAX_CHARACTER_COUNT 16
#define MIN_CHARACTER_NAME_LENGTH 4
#define MAX_CHARACTER_NAME_LENGTH 16
#define MAX_CHARACTER_QUICK_SLOT_COUNT 296
#define MAX_CHARACTER_NORMAL_FACE_COUNT 4
#define MAX_CHARACTER_NORMAL_HAIR_COUNT 7
#define MAX_CHARACTER_NORMAL_HAIR_COLOR_COUNT 8

#define MAX_SECRET_SHOP_COUNT 5

#define TERRAIN_SIZE				256
#define TERRAIN_SIZE_EXPONENT		8
#define TILE_SIZE					16
#define TILE_SIZE_EXPONENT			4
#define TILE_SIZE_MASK				0x0000000F

#define MOVEMENT_ERROR_TOLERANCE_SQUARE 256

#define MAX_WAYPOINT_COUNT 32

#define MIN_SUBPASSWORD_LENGTH 4
#define MAX_SUBPASSWORD_LENGTH 10
#define MIN_SUBPASSWORD_ANSWER_LENGTH 1
#define MAX_SUBPASSWORD_ANSWER_LENGTH 128

#define SERVER_CHARACTER_CHUNK_VIEW_RADIUS			4
#define SERVER_CHARACTER_MAX_BUY_ITEM_COUNT			50
#define SERVER_CHARACTER_MAX_BUY_ITEM_PRICE_COUNT	522
#define SERVER_CHARACTER_MAX_SELL_ITEM_COUNT		100

#define SERVER_DBSYNC_TIMEOUT_PRIORITY_LOW   1000 * 10
#define SERVER_DBSYNC_TIMEOUT_PRIORITY_HIGH  1000 * 60

EXTERN_C_END