#pragma once

#include <CoreLib/CoreLib.h>

EXTERN_C_BEGIN

enum {
    ACCOUNT_STATUS_NORMAL = 0x20,
    ACCOUNT_STATUS_INVALID_CREDENTIALS,
    ACCOUNT_STATUS_ALREADY_LOGGED_IN,
    ACCOUNT_STATUS_OUT_OF_SERVICE,
    ACCOUNT_STATUS_ACCOUNT_EXPIRED,
    ACCOUNT_STATUS_IP_BANNED,
    ACCOUNT_STATUS_ACCOUNT_BANNED,
    ACCOUNT_STATUS_TEST_SERVER_TRIAL,
    ACCOUNT_STATUS_PC_CAFE,
    ACCOUNT_STATUS_ACCOUNT_NOT_VERIFIED,
    ACCOUNT_STATUS_ACCOUNT_IS_DELETED,
    ACCOUNT_STATUS_ACCOUNT_IS_LOCKED,
};

enum {
    LOGIN_STATUS_ERROR = 0,
    LOGIN_STATUS_SUCCESS = 1,
};

enum {
    SERVER_STATUS_ONLINE,
    SERVER_STATUS_MAINTENANCE,
    SERVER_STATUS_UNAVAILABLE,
};

enum {
    CREATE_CHARACTER_STATUS_DBERROR                 = 1,
    CREATE_CHARACTER_STATUS_NAME_OCCUPIED           = 3,
    CREATE_CHARACTER_STATUS_NAME_VALIDATION_FAILED  = 4,
    CREATE_CHARACTER_STATUS_NOT_ALLOWED             = 5,
    CREATE_CHARACTER_STATUS_SUCCESS                 = 0xA8,
};

enum {
    WORLD_TYPE_NONE             = 0x00,
    WORLD_TYPE_PREMIUM          = 0x04,
    WORLD_TYPE_NATION           = 0x08,
    WORLD_TYPE_WAR              = 0x10,
    WORLD_TYPE_RESTRICTED       = 0x20,
    WORLD_TYPE_WAR_LOBBY_START  = 0x40,
    WORLD_TYPE_WAR_LOBBY_END    = 0x80,
    WORLD_TYPE_WAR_LOBBY_CLOSED = 0x100,
    WORLD_TYPE_WAR_CLOSED       = 0x200,
    WORLD_TYPE_TRADE            = 0x400,
};

enum {
    STORAGE_TYPE_INVENTORY = 0,
    STORAGE_TYPE_EQUIPMENT = 1,
    STORAGE_TYPE_WAREHOUSE = 2,
    STORAGE_TYPE_VEHICLE_INVENTORY = 4,
};

enum {
    DBSYNC_CHARACTER_DATA           = 1 << 0,
    DBSYNC_CHARACTER_EQUIPMENT      = 1 << 1,
    DBSYNC_CHARACTER_INVENTORY      = 1 << 2,
    DBSYNC_CHARACTER_SKILLSLOT      = 1 << 3,
    DBSYNC_CHARACTER_QUICKSLOT      = 1 << 4,
    DBSYNC_CHARACTER_QUESTDATA      = 1 << 5,
    DBSYNC_CHARACTER_QUESTFLAG      = 1 << 6,
    DBSYNC_CHARACTER_ACHIEVEMENT    = 1 << 7,
    DBSYNC_CHARACTER_ESSENCERUNE    = 1 << 8,
    DBSYNC_CHARACTER_BLENDEDRUNE    = 1 << 9,
    DBSYNC_CHARACTER_HONORMEDAL     = 1 << 10,
    DBSYNC_CHARACTER_OVERLORD       = 1 << 11,
    DBSYNC_CHARACTER_TRANSFORM      = 1 << 12,
    DBSYNC_CHARACTER_TRANSCENDENCE  = 1 << 13,
    DBSYNC_CHARACTER_MERCENARY      = 1 << 14,
    DBSYNC_CHARACTER_CRAFT          = 1 << 15,

    DBSYNC_ACCOUNT_ACHIEVEMENT      = 1 << 16,
    DBSYNC_ACCOUNT_WAREHOUSE        = 1 << 17,
    DBSYNC_ACCOUNT_MERIT            = 1 << 18,
    DBSYNC_ACCOUNT_COLLECTION       = 1 << 19,
};

enum {
    CHARACTER_SUBPASSWORD_TYPE_CHARACTER = 1,
};

enum {
    CHARACTER_NATION_MASK_NONE          = 0,
    CHARACTER_NATION_MASK_NEUTRAL       = 1 << 0,
    CHARACTER_NATION_MASK_CAPELLA       = 1 << 1,
    CHARACTER_NATION_MASK_PROCYON       = 1 << 2,
    CHARACTER_NATION_MASK_GAMEMASTER    = 1 << 3,
};

enum {
    EQUIPMENT_SLOT_INDEX_HELMED                         = 0,
    EQUIPMENT_SLOT_INDEX_SUIT                           = 1,
    EQUIPMENT_SLOT_INDEX_GLOVES                         = 2,
    EQUIPMENT_SLOT_INDEX_BOOTS                          = 3,
    EQUIPMENT_SLOT_INDEX_WEAPON_LEFT_HAND               = 4,
    EQUIPMENT_SLOT_INDEX_WEAPON_RIGHT_HAND              = 5,
    EQUIPMENT_SLOT_INDEX_EPAULET                        = 6,
    EQUIPMENT_SLOT_INDEX_AMULETT                        = 7,
    EQUIPMENT_SLOT_INDEX_RING_TOP_LEFT                  = 8,
    EQUIPMENT_SLOT_INDEX_RING_TOP_RIGHT                 = 9,
    EQUIPMENT_SLOT_INDEX_VEHICLE                        = 10,
    EQUIPMENT_SLOT_INDEX_PET                            = 11,

    EQUIPMENT_SLOT_INDEX_EARRING_LEFT                   = 13,
    EQUIPMENT_SLOT_INDEX_EARRING_RIGHT                  = 14,
    EQUIPMENT_SLOT_INDEX_BRACELET_LEFT                  = 15,
    EQUIPMENT_SLOT_INDEX_BRACELET_RIGHT                 = 16,
    EQUIPMENT_SLOT_INDEX_RING_LEFT_BOTTOM               = 17,
    EQUIPMENT_SLOT_INDEX_RING_RIGHT_BOTTOM              = 18,
    EQUIPMENT_SLOT_INDEX_BELT                           = 19,
    EQUIPMENT_SLOT_INDEX_PET_EXTENDER                   = 20,
    EQUIPMENT_SLOT_INDEX_CHARM                          = 21,
    EQUIPMENT_SLOT_INDEX_EFFECTOR_LEFT                  = 22,
    EQUIPMENT_SLOT_INDEX_EFFECTOR_RIGHT                 = 23,
    EQUIPMENT_SLOT_INDEX_LINKED_WEAPON                  = 24,
    EQUIPMENT_SLOT_INDEX_DISPLAYED_COSTUME_SLOT_4       = 25,
    EQUIPMENT_SLOT_INDEX_DISPLAYED_COSTUME_SLOT_3       = 26,
    EQUIPMENT_SLOT_INDEX_DISPLAYED_COSTUME_SLOT_2       = 27,
    EQUIPMENT_SLOT_INDEX_APPLIED_COSTUME_SLOT_1         = 28,
    EQUIPMENT_SLOT_INDEX_DIALOG_BUBBLE                  = 29,
    EQUIPMENT_SLOT_INDEX_TALISMAN                       = 30,
    EQUIPMENT_SLOT_INDEX_DISPLAYED_COSTUME_SLOT_1       = 31,
    EQUIPMENT_SLOT_INDEX_CARNELIAN                      = 32,
    EQUIPMENT_SLOT_INDEX_ARCANA_LEFT                    = 33,
    EQUIPMENT_SLOT_INDEX_ARCANA_RIGHT                   = 34,

    EQUIPMENT_SLOT_INDEX_DISPLAYED_COSTUME_VEHICLE      = 36,
    EQUIPMENT_SLOT_INDEX_APPLIED_COSTUME_FORCE_WING     = 37,
    EQUIPMENT_SLOT_INDEX_DISPLAYED_COSTUME_FORCE_WING   = 38,
    EQUIPMENT_SLOT_INDEX_DISPLAYED_PET                  = 39,
    EQUIPMENT_SLOT_INDEX_BADGE                          = 40,
    EQUIPMENT_SLOT_INDEX_CUBE_SLOT_1                    = 41,
    EQUIPMENT_SLOT_INDEX_CUBE_SLOT_2                    = 42,
    EQUIPMENT_SLOT_INDEX_CUBE_SLOT_3                    = 43,

};

EXTERN_C_END
