#pragma once

#include <CoreLib/CoreLib.h>

EXTERN_C_BEGIN

enum {
    ACCOUNT_STATUS_NORMAL = 0x20,
    ACCOUNT_STATUS_INVALID_CREDENTIALS,
    ACCOUNT_STATUS_ALREADY_LOGGED_IN,
    ACCOUNT_STATUS_OUT_OF_SERVICE,
    ACCOUNT_STATUS_ACCOUNT_EXPIRED,
    ACCOUNT_STATUS_IP_BANNED,
    ACCOUNT_STATUS_ACCOUNT_BANNED,
    ACCOUNT_STATUS_TEST_SERVER_TRIAL,
    ACCOUNT_STATUS_PC_CAFE,
    ACCOUNT_STATUS_ACCOUNT_NOT_VERIFIED,
    ACCOUNT_STATUS_ACCOUNT_IS_DELETED,
    ACCOUNT_STATUS_ACCOUNT_IS_LOCKED,
};

enum {
    LOGIN_STATUS_ERROR = 0,
    LOGIN_STATUS_SUCCESS = 1,
};

enum {
    SERVER_STATUS_ONLINE,
    SERVER_STATUS_MAINTENANCE,
    SERVER_STATUS_UNAVAILABLE,
};

enum {
    CREATE_CHARACTER_STATUS_DBERROR                 = 1,
    CREATE_CHARACTER_STATUS_NAME_OCCUPIED           = 3,
    CREATE_CHARACTER_STATUS_NAME_VALIDATION_FAILED  = 4,
    CREATE_CHARACTER_STATUS_NOT_ALLOWED             = 5,
    CREATE_CHARACTER_STATUS_SUCCESS                 = 0xA8,
};

enum {
    WORLD_TYPE_NONE             = 0x00,
    WORLD_TYPE_PREMIUM          = 0x04,
    WORLD_TYPE_NATION           = 0x08,
    WORLD_TYPE_WAR              = 0x10,
    WORLD_TYPE_RESTRICTED       = 0x20,
    WORLD_TYPE_WAR_LOBBY_START  = 0x40,
    WORLD_TYPE_WAR_LOBBY_END    = 0x80,
    WORLD_TYPE_WAR_LOBBY_CLOSED = 0x100,
    WORLD_TYPE_WAR_CLOSED       = 0x200,
    WORLD_TYPE_TRADE            = 0x400,
};

enum {
    STORAGE_TYPE_INVENTORY = 0,
    STORAGE_TYPE_EQUIPMENT = 1,
    STORAGE_TYPE_WAREHOUSE = 2,
    STORAGE_TYPE_VEHICLE_INVENTORY = 4,
};

enum {
    CHARACTER_SUBPASSWORD_TYPE_CHARACTER = 1,
};

enum {
    CHARACTER_NATION_MASK_NONE          = 0,
    CHARACTER_NATION_MASK_NEUTRAL       = 1 << 0,
    CHARACTER_NATION_MASK_CAPELLA       = 1 << 1,
    CHARACTER_NATION_MASK_PROCYON       = 1 << 2,
    CHARACTER_NATION_MASK_GAMEMASTER    = 1 << 3,
};

EXTERN_C_END
