#include "BattleSystem.h"
#include "Character.h"
#include "Constants.h"
#include "Force.h"

struct _RTForceEffectFormula {
	Int32 ForceEffectID;
	UInt8 ForceEffectType;
	Int32 Attributes[RUNTIME_MAX_FORCE_EFFECT_CODE_COUNT];
};

struct _RTForceEffectFormula kForceEffectFormulas[RUNTIME_FORCE_EFFECT_COUNT];

// TODO: This is just for debugging read this from xml file
Void RTInitForceEffectFormulas() {
	memset(kForceEffectFormulas, 0, sizeof(kForceEffectFormulas));

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ATTACK_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_ATTACK_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ATTACK_UP].Attributes[0] = RUNTIME_ATTRIBUTE_ATTACK;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP].Attributes[0] = RUNTIME_ATTRIBUTE_MAGIC_ATTACK;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP].Attributes[0] = RUNTIME_ATTRIBUTE_ATTACK_RATE;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_DEFENSE_RATE_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_DEFENSE_RATE_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_DEFENSE_RATE_UP].Attributes[0] = RUNTIME_ATTRIBUTE_DEFENSE_RATE;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_UP].Attributes[0] = RUNTIME_ATTRIBUTE_CRITICAL_DAMAGE;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ATTACK_UP2].ForceEffectID = RUNTIME_FORCE_EFFECT_ATTACK_UP2;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ATTACK_UP2].Attributes[0] = RUNTIME_ATTRIBUTE_ATTACK;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP2].ForceEffectID = RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP2;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP2].Attributes[0] = RUNTIME_ATTRIBUTE_MAGIC_ATTACK;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_CRITICAL_RATE_LIMIT_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_CRITICAL_RATE_LIMIT_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_CRITICAL_RATE_LIMIT_UP].Attributes[0] = RUNTIME_ATTRIBUTE_CRITICAL_RATE_MAX;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP2].ForceEffectID = RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP2;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP2].Attributes[0] = RUNTIME_ATTRIBUTE_ATTACK_RATE;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ADD_DAMAGE].ForceEffectID = RUNTIME_FORCE_EFFECT_ADD_DAMAGE;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ADD_DAMAGE].Attributes[0] = RUNTIME_ATTRIBUTE_ADD_DAMAGE;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION].ForceEffectID = RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION].Attributes[0] = RUNTIME_ATTRIBUTE_DAMAGE_REDUCTION;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ACCURACY].ForceEffectID = RUNTIME_FORCE_EFFECT_ACCURACY;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ACCURACY].Attributes[0] = RUNTIME_ATTRIBUTE_ACCURACY;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_PENETRATION].ForceEffectID = RUNTIME_FORCE_EFFECT_PENETRATION;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_PENETRATION].Attributes[0] = RUNTIME_ATTRIBUTE_PENETRATION;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_IGNORE_RESIST_CRITICAL_RATE].ForceEffectID = RUNTIME_FORCE_EFFECT_IGNORE_RESIST_CRITICAL_RATE;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_IGNORE_RESIST_CRITICAL_RATE].Attributes[0] = RUNTIME_ATTRIBUTE_IGNORE_RESIST_CRITICAL_RATE;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_DEFENSE_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_DEFENSE_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_DEFENSE_UP].Attributes[0] = RUNTIME_ATTRIBUTE_DEFENSE;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_HP_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_HP_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_HP_UP].Attributes[0] = RUNTIME_ATTRIBUTE_HP_MAX;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_KNOCK_BACK].ForceEffectID = RUNTIME_FORCE_EFFECT_RESIST_KNOCK_BACK;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_KNOCK_BACK].Attributes[0] = RUNTIME_ATTRIBUTE_RESIST_KNOCK_BACK;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_IGNORE_ACCURACY].ForceEffectID = RUNTIME_FORCE_EFFECT_IGNORE_ACCURACY;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_IGNORE_ACCURACY].Attributes[0] = RUNTIME_ATTRIBUTE_IGNORE_ACCURACY;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_IGNORE_PENETRATION].ForceEffectID = RUNTIME_FORCE_EFFECT_IGNORE_PENETRATION;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_IGNORE_PENETRATION].Attributes[0] = RUNTIME_ATTRIBUTE_IGNORE_PENETRATION;
	
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_CRITICAL_DAMAGE].ForceEffectID = RUNTIME_FORCE_EFFECT_RESIST_CRITICAL_DAMAGE;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_CRITICAL_DAMAGE].Attributes[0] = RUNTIME_ATTRIBUTE_RESIST_CRITICAL_DAMAGE;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_DOWN].ForceEffectID = RUNTIME_FORCE_EFFECT_RESIST_DOWN;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_DOWN].Attributes[0] = RUNTIME_ATTRIBUTE_RESIST_DOWN;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_STUN].ForceEffectID = RUNTIME_FORCE_EFFECT_RESIST_STUN;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_STUN].Attributes[0] = RUNTIME_ATTRIBUTE_RESIST_STUN;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_SKILL_AMP].ForceEffectID = RUNTIME_FORCE_EFFECT_RESIST_SKILL_AMP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_RESIST_SKILL_AMP].Attributes[0] = RUNTIME_ATTRIBUTE_RESIST_SKILL_AMP;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ALL_ATTACK_UP].ForceEffectID = RUNTIME_FORCE_EFFECT_ALL_ATTACK_UP;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ALL_ATTACK_UP].Attributes[0] = RUNTIME_ATTRIBUTE_ATTACK;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ALL_ATTACK_UP].Attributes[1] = RUNTIME_ATTRIBUTE_MAGIC_ATTACK;

	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ALL_ATTACK_UP2].ForceEffectID = RUNTIME_FORCE_EFFECT_ALL_ATTACK_UP2;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ALL_ATTACK_UP2].Attributes[0] = RUNTIME_ATTRIBUTE_ATTACK;
	kForceEffectFormulas[RUNTIME_FORCE_EFFECT_ALL_ATTACK_UP2].Attributes[1] = RUNTIME_ATTRIBUTE_MAGIC_ATTACK;
}

Void RTCharacterApplyForceEffect(
	RTRuntimeRef Runtime,
	RTCharacterRef Character,
	Int32 ForceEffect,
	Int32 ForceValue,
	Int32 ForceValueType
) {
	// TODO: Eval ForceValueType

	assert(0 <= ForceEffect && ForceEffect < RUNTIME_FORCE_EFFECT_COUNT);

	struct _RTForceEffectFormula* Formula = &kForceEffectFormulas[ForceEffect];
	if (!Formula) return;

	assert(Formula->ForceEffectID);

	for (Int32 Index = 0; Index < RUNTIME_MAX_FORCE_EFFECT_CODE_COUNT; Index += 1) {
		Int32 AttributeIndex = Formula->Attributes[Index];
		if (!AttributeIndex) break;

		switch (Formula->ForceEffectType) {
		case RUNTIME_FORCE_VALUE_TYPE_ADDITIVE:
			Character->Attributes.Values[AttributeIndex] += ForceValue;
			break;

		case RUNTIME_FORCE_VALUE_TYPE_MULTIPLICATIVE: // TODO: Is this even a thing at all?
			break;
		}

		assert(0 <= AttributeIndex && AttributeIndex < RUNTIME_ATTRIBUTE_COUNT);
	}
}

Void RTCharacterCancelForceEffect(
	RTRuntimeRef Runtime,
	RTCharacterRef Character,
	Int32 ForceEffect,
	Int32 ForceValue,
	Int32 ForceValueType
) {

}