#pragma once

#include "Base.h"
#include "Constants.h"
#include "Entity.h"

EXTERN_C_BEGIN

#pragma pack(push, 1)

enum {
	RUNTIME_FORCE_EFFECT_NONE = 0,

	RUNTIME_FORCE_EFFECT_LEVEL_DOWN = 61,

	RUNTIME_FORCE_EFFECT_STR_UP = 45,
	RUNTIME_FORCE_EFFECT_INT_UP = 46,
	RUNTIME_FORCE_EFFECT_DEX_UP = 47,
	RUNTIME_FORCE_EFFECT_STR_DEX_INT_UP = 48,

	RUNTIME_FORCE_EFFECT_HP_UP_1 = 1,
	RUNTIME_FORCE_EFFECT_HP_UP_2 = 60,
	RUNTIME_FORCE_EFFECT_HP_UP_3 = 171,
	RUNTIME_FORCE_EFFECT_HP_ABSORB_UP = 34,
	RUNTIME_FORCE_EFFECT_HP_ABSORB_LIMIT_UP = 12,
	RUNTIME_FORCE_EFFECT_HP_REGEN = 37,
	RUNTIME_FORCE_EFFECT_HP_REGEN_UP = 124,
	RUNTIME_FORCE_EFFECT_HP_REGEN_DOWN = 166,
	RUNTIME_FORCE_EFFECT_HP_CURSE = 95,
	RUNTIME_FORCE_EFFECT_HP_CURSE_RESIST = 143,
	RUNTIME_FORCE_EFFECT_HP_HEAL = 63,
	RUNTIME_FORCE_EFFECT_HP_HEAL_UP = 159,
	RUNTIME_FORCE_EFFECT_HP_HEAL_DOWN = 165,

	RUNTIME_FORCE_EFFECT_MP_UP = 2,
	RUNTIME_FORCE_EFFECT_MP_ABSORB_UP = 35,
	RUNTIME_FORCE_EFFECT_MP_ABSORB_LIMIT_UP = 13,
	RUNTIME_FORCE_EFFECT_MP_REGEN = 38,
	RUNTIME_FORCE_EFFECT_MP_CURSE = 96,

	RUNTIME_FORCE_EFFECT_SP_REGEN_UP = 88,
	RUNTIME_FORCE_EFFECT_SP_CONSUMPTION_DOWN = 89,

	RUNTIME_FORCE_EFFECT_BP_LIMIT_UP = 144,
	RUNTIME_FORCE_EFFECT_BP_CONSUMPTION_DOWN = 145,

	RUNTIME_FORCE_EFFECT_RAGE_UP = 164,

	RUNTIME_FORCE_EFFECT_ATTACK_UP_1 = 3,
	RUNTIME_FORCE_EFFECT_ATTACK_UP_2 = 23,
	RUNTIME_FORCE_EFFECT_ATTACK_UP_3 = 224,
	RUNTIME_FORCE_EFFECT_ATTACK_UP_PVP = 176,
	RUNTIME_FORCE_EFFECT_ATTACK_UP_PVE = 177,

	RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP_1 = 4,
	RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP_2 = 24,
	RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP_3 = 225,
	RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP_PVP = 178,
	RUNTIME_FORCE_EFFECT_MAGIC_ATTACK_UP_PVE = 179,

	RUNTIME_FORCE_EFFECT_FINAL_ATTACK_UP_1 = 58,
	RUNTIME_FORCE_EFFECT_FINAL_ATTACK_UP_2 = 113,
	RUNTIME_FORCE_EFFECT_FINAL_ATTACK_UP_3 = 115,
	RUNTIME_FORCE_EFFECT_FINAL_ATTACK_UP_PVP = 180,
	RUNTIME_FORCE_EFFECT_FINAL_ATTACK_UP_PVE = 181,
	RUNTIME_FORCE_EFFECT_FINAL_ATTACK_UP_PERCENT = 222,

	RUNTIME_FORCE_EFFECT_DEFENSE_UP_1 = 5,
	RUNTIME_FORCE_EFFECT_DEFENSE_UP_2 = 59,
	RUNTIME_FORCE_EFFECT_DEFENSE_UP_PVP = 189,
	RUNTIME_FORCE_EFFECT_DEFENSE_UP_PVE = 155,
	RUNTIME_FORCE_EFFECT_DEFENSE_UP_PERCENT = 223,

	RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP_1 = 6,
	RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP_2 = 26,
	RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP_PVP = 182,
	RUNTIME_FORCE_EFFECT_ATTACK_RATE_UP_PVE = 183,

	RUNTIME_FORCE_EFFECT_DEFENSE_RATE_UP_1 = 7,
	RUNTIME_FORCE_EFFECT_DEFENSE_RATE_UP_PVP = 190,
	RUNTIME_FORCE_EFFECT_DEFENSE_RATE_UP_PVE = 191,

	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_UP_1 = 9,
	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_UP_2 = 29,
	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_UP_PVP = 184,
	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_UP_PVE = 185,
	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_RESIST = 97,
	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_IGNORE_RESIST = 125,
	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_IGNORE_RESIST_PVP = 218,
	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_IGNORE_RESIST_PVE = 219,
	RUNTIME_FORCE_EFFECT_CRITICAL_RATE_LIMIT_UP = 25,

	RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_UP_1 = 8,
	RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_UP_2 = 28,
	RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_UP_PVP = 173,
	RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_UP_PVE = 158,
	RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_RESIST = 98,
	RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_IGNORE_RESIST = 127,
	RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_IGNORE_RESIST_PVP = 206,
	RUNTIME_FORCE_EFFECT_CRITICAL_DAMAGE_IGNORE_RESIST_PVE = 207,

	RUNTIME_FORCE_EFFECT_NORMAL_DAMAGE_UP = 132,
	RUNTIME_FORCE_EFFECT_NORMAL_DAMAGE_UP_PVP = 198,
	RUNTIME_FORCE_EFFECT_NORMAL_DAMAGE_UP_PVE = 199,

	RUNTIME_FORCE_EFFECT_MIN_DAMAGE_UP_1 = 10,
	RUNTIME_FORCE_EFFECT_MIN_DAMAGE_UP_2 = 11,

	RUNTIME_FORCE_EFFECT_SWORD_SKILL_AMP_UP_1 = 30,
	RUNTIME_FORCE_EFFECT_SWORD_SKILL_AMP_UP_2 = 31,
	RUNTIME_FORCE_EFFECT_SWORD_SKILL_AMP_UP_PVP = 175,
	RUNTIME_FORCE_EFFECT_SWORD_SKILL_AMP_RESIST_PVP = 149,
	RUNTIME_FORCE_EFFECT_SWORD_SKILL_AMP_RESIST_PVE = 152,

	RUNTIME_FORCE_EFFECT_MAGIC_SKILL_AMP_UP_1 = 32,
	RUNTIME_FORCE_EFFECT_MAGIC_SKILL_AMP_UP_2 = 33,
	RUNTIME_FORCE_EFFECT_MAGIC_SKILL_AMP_UP_PVP = 174,
	RUNTIME_FORCE_EFFECT_MAGIC_SKILL_AMP_RESIST_PVP = 148,
	RUNTIME_FORCE_EFFECT_MAGIC_SKILL_AMP_RESIST_PVE = 151,

	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_UP_1 = 114,
	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_UP_2 = 116,
	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_UP_PVP = 172,
	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_UP_PVE = 153,
	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_RESIST = 112,
	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_RESIST_PVP = 150,
	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_IGNORE_RESIST = 128,
	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_IGNORE_RESIST_PVP = 214,
	RUNTIME_FORCE_EFFECT_ALL_SKILL_AMP_IGNORE_RESIST_PVE = 215,

	RUNTIME_FORCE_EFFECT_EVASION_UP = 36,
	RUNTIME_FORCE_EFFECT_EVASION_UP_PVP = 192,
	RUNTIME_FORCE_EFFECT_EVASION_UP_PVE = 193,
	RUNTIME_FORCE_EFFECT_EVASION_RESIST = 71,
	RUNTIME_FORCE_EFFECT_EVASION_RESIST_PVP = 212,
	RUNTIME_FORCE_EFFECT_EVASION_RESIST_PVE = 213,
	RUNTIME_FORCE_EFFECT_EVASION_IGNORE_RESIST = 75,
	RUNTIME_FORCE_EFFECT_EVASION_ABSOLUTE = 136,
	RUNTIME_FORCE_EFFECT_EVASION_COMPLETE = 92,

	RUNTIME_FORCE_EFFECT_ADD_DAMAGE_UP_1 = 39,
	RUNTIME_FORCE_EFFECT_ADD_DAMAGE_UP_2 = 40,
	RUNTIME_FORCE_EFFECT_ADD_DAMAGE_UP_PVP = 202,
	RUNTIME_FORCE_EFFECT_ADD_DAMAGE_UP_PVE = 203,

	RUNTIME_FORCE_EFFECT_FINAL_DAMAGE_UP = 56,
	RUNTIME_FORCE_EFFECT_FINAL_DAMAGE_UP_PVP = 200,
	RUNTIME_FORCE_EFFECT_FINAL_DAMAGE_UP_PVE = 201,

	RUNTIME_FORCE_EFFECT_FINAL_DAMAGE_DOWN = 57,
	RUNTIME_FORCE_EFFECT_FINAL_DAMAGE_DOWN_PVP = 196,
	RUNTIME_FORCE_EFFECT_FINAL_DAMAGE_DOWN_PVE = 197,

	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION = 78,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_PVP = 194,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_PVE = 156,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_PERCENT = 162,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_RESIST = 73,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_RESIST_PVP = 216,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_RESIST_PVE = 217,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_IGNORE_RESIST = 81,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_IGNORE_RESIST_PVP = 204,
	RUNTIME_FORCE_EFFECT_DAMAGE_REDUCTION_IGNORE_RESIST_PVE = 205,

	RUNTIME_FORCE_EFFECT_ACCURACY = 79,
	RUNTIME_FORCE_EFFECT_ACCURACY_PVP = 186,
	RUNTIME_FORCE_EFFECT_ACCURACY_PVE = 187,
	RUNTIME_FORCE_EFFECT_ACCURACY_RESIST = 72,
	RUNTIME_FORCE_EFFECT_ACCURACY_RESIST_PVP = 210,
	RUNTIME_FORCE_EFFECT_ACCURACY_RESIST_PVE = 211,

	RUNTIME_FORCE_EFFECT_PENETRATION = 80,
	RUNTIME_FORCE_EFFECT_PENETRATION_PVP = 188,
	RUNTIME_FORCE_EFFECT_PENETRATION_PVE = 163,
	RUNTIME_FORCE_EFFECT_PENETRATION_RESIST = 74,
	RUNTIME_FORCE_EFFECT_PENETRATION_RESIST_PVP = 195,
	RUNTIME_FORCE_EFFECT_PENETRATION_RESIST_PVE = 157,
	RUNTIME_FORCE_EFFECT_PENETRATION_IGNORE_RESIST = 139,
	RUNTIME_FORCE_EFFECT_PENETRATION_IGNORE_RESIST_PVP = 208,
	RUNTIME_FORCE_EFFECT_PENETRATION_IGNORE_RESIST_PVE = 209,

	RUNTIME_FORCE_EFFECT_STUN = 62,
	RUNTIME_FORCE_EFFECT_STUN_RESIST = 103,
	RUNTIME_FORCE_EFFECT_STUN_IGNORE_RESIST = 131,

	RUNTIME_FORCE_EFFECT_DOWN = 64,
	RUNTIME_FORCE_EFFECT_DOWN_RESIST = 101,
	RUNTIME_FORCE_EFFECT_DOWN_IGNORE_RESIST = 129,

	RUNTIME_FORCE_EFFECT_KNOCK_BACK = 65,
	RUNTIME_FORCE_EFFECT_KNOCK_BACK_RESIST = 102,
	RUNTIME_FORCE_EFFECT_KNOCK_BACK_IGNORE_RESIST = 130,
	
	RUNTIME_FORCE_EFFECT_IMMOBILITY = 66,
	RUNTIME_FORCE_EFFECT_IMMOBILITY_RESIST = 99,
	RUNTIME_FORCE_EFFECT_IMMOBILITY_REMOVE = 54,
	
	RUNTIME_FORCE_EFFECT_SUPPRESSION = 84, // When Suppression is in effect, afflicted character cannot move or use skills.
	RUNTIME_FORCE_EFFECT_SUPPRESSION_PERCENT = 118,
	RUNTIME_FORCE_EFFECT_SUPPRESSION_DURATION = 119,
	RUNTIME_FORCE_EFFECT_SUPPRESSION_RESIST = 83,

	RUNTIME_FORCE_EFFECT_SILENCE = 87, // When Silence is in effect, afflicted character cannot use any skills.
	RUNTIME_FORCE_EFFECT_SILENCE_PERCENT = 120,
	RUNTIME_FORCE_EFFECT_SILENCE_DURATION = 121,
	RUNTIME_FORCE_EFFECT_SILENCE_RESIST = 85,

	RUNTIME_FORCE_EFFECT_ROOT = 86, // When Root is in effect, afflicted character cannot move or use skills related to movement.
	RUNTIME_FORCE_EFFECT_ROOT_PERCENT = 122,
	RUNTIME_FORCE_EFFECT_ROOT_DURATION = 123,

	RUNTIME_FORCE_EFFECT_PETRIFY = 168,

	RUNTIME_FORCE_EFFECT_DAMAGE_ABSORB = 67,
	RUNTIME_FORCE_EFFECT_DAMAGE_REFLECT_1 = 68,
	RUNTIME_FORCE_EFFECT_DAMAGE_REFLECT_2 = 100,

	RUNTIME_FORCE_EFFECT_MOVEMENT_SPEED_UP = 117,
	RUNTIME_FORCE_EFFECT_MOVEMENT_SPEED_PERCENT = 167,

	RUNTIME_FORCE_EFFECT_WING_DAMAGE_UP = 133,
	RUNTIME_FORCE_EFFECT_WING_DAMAGE_ACTIVATE = 134,
	RUNTIME_FORCE_EFFECT_WING_PROTECT_ACTIVATE = 135,

	RUNTIME_FORCE_EFFECT_ABSOLUTE_BLOCK = 137,
	RUNTIME_FORCE_EFFECT_ABSOLUTE_DAMAGE_RESIST = 126,

	RUNTIME_FORCE_EFFECT_CRAFT_MASTERY_UP = 69,

	RUNTIME_FORCE_EFFECT_BATTLE_MODE_DURATION_UP = 70,
	RUNTIME_FORCE_EFFECT_AURA_MODE_DURATION_UP = 138,

	RUNTIME_FORCE_EFFECT_EVADE_DEBUFF_SKILL = 55,

	RUNTIME_FORCE_EFFECT_ATTACK_RANGE_DOWN = 82,

	RUNTIME_FORCE_EFFECT_MEZZ_IMMUNE = 91, // Character cannot be afflicted by status changes.

	RUNTIME_FORCE_EFFECT_AGGRO_UP = 93,

	RUNTIME_FORCE_EFFECT_GRANT_WEAPON_OPTION = 94, // Force Blader Blade Buffs

	RUNTIME_FORCE_EFFECT_INVINCIBLE_MODE = 104,

	RUNTIME_FORCE_EFFECT_SKILL_EXP_UP_1 = 41,
	RUNTIME_FORCE_EFFECT_SKILL_EXP_UP_2 = 42,
	RUNTIME_FORCE_EFFECT_SKILL_EXP_UP_PERCENT = 77,

	RUNTIME_FORCE_EFFECT_ALZ_DROP_AMOUNT_UP_1 = 43,
	RUNTIME_FORCE_EFFECT_ALZ_DROP_AMOUNT_UP_2 = 44,
	RUNTIME_FORCE_EFFECT_ALZ_DROP_RATE_UP = 109,
	RUNTIME_FORCE_EFFECT_ALZ_BOMB_RATE_UP = 110,

	RUNTIME_FORCE_EFFECT_DROP_RATE_UP_1 = 49,
	RUNTIME_FORCE_EFFECT_DROP_RATE_UP_2 = 50,

	RUNTIME_FORCE_EFFECT_BOX_DROP_RATE_UP_1 = 51,
	RUNTIME_FORCE_EFFECT_BOX_DROP_RATE_UP_2 = 52,
	RUNTIME_FORCE_EFFECT_BOX_DROP_RATE_UP_3 = 142,

	RUNTIME_FORCE_EFFECT_AXP_BONUS = 76,
	RUNTIME_FORCE_EFFECT_WAR_EXP_BONUS = 105,
	RUNTIME_FORCE_EFFECT_WAR_EXP_UP2 = 140,
	RUNTIME_FORCE_EFFECT_PARTY_EXP_BONUS = 106,
	RUNTIME_FORCE_EFFECT_EXP_BONUS = 107,
	RUNTIME_FORCE_EFFECT_PET_EXP_BONUS = 108,
	RUNTIME_FORCE_EFFECT_FORCE_WING_EXP_UP = 141,

	RUNTIME_FORCE_EFFECT_MERIT_SPECIAL_MASTERY_UNKNOWN_146 = 146,
	RUNTIME_FORCE_EFFECT_POISON_MIST_RAY = 147,
	RUNTIME_FORCE_EFFECT_NUMBER_OF_TARGET_FOR_VALID_SKILL = 154,
	RUNTIME_FORCE_EFFECT_DEDUCT_PROTECTION = 160,
	RUNTIME_FORCE_EFFECT_FLUIDIZATION = 161,
	RUNTIME_FORCE_EFFECT_TARGET_FIX = 169,
	RUNTIME_FORCE_EFFECT_RESIST_IRRECOVERABLE_CONDITION = 170,
	
	RUNTIME_FORCE_EFFECT_ARRIVAL_SKILL_COOLTIME_DOWN = 220,
	RUNTIME_FORCE_EFFECT_ARRIVAL_SKILL_BUFFTIME_UP = 221,
	RUNTIME_FORCE_EFFECT_UNKNOWN_226 = 226, // maybe: New Force Code: "Resist Stone Curse" added (minimum 5% ~ maximum 9%).
	RUNTIME_FORCE_EFFECT_COUNT,
};

enum {
	RUNTIME_FORCE_EFFECT_TYPE_ADDITIVE = 1,
	RUNTIME_FORCE_EFFECT_TYPE_MULTIPLICATIVE = 2,
	RUNTIME_FORCE_EFFECT_TYPE_STATUS = 3,
	RUNTIME_FORCE_EFFECT_TYPE_MAXIMUM_INCREASE = 4,
};

enum {
	RUNTIME_FORCE_VALUE_TYPE_ADDITIVE = 0,
	RUNTIME_FORCE_VALUE_TYPE_MULTIPLICATIVE = 1,
};

typedef Void (*RTForceEffectFormulaCallback)(
    RTRuntimeRef Runtime,
    RTForceEffectFormulaRef Formula,
	RTEntityID Source,
    RTBattleAttributesRef Attributes,
    Int64 Value
);

struct _RTForceEffectFormula {
	Int ForceEffectIndex;
	Int AttributeCount;
	Int AttributeIndices[RUNTIME_MAX_FORCE_EFFECT_ATTRIBUTE_COUNT];
	RTForceEffectFormulaCallback OnApply;
    RTForceEffectFormulaCallback OnCancel;
};

#pragma pack(pop)

Void RTRuntimeInitForceEffectFormulas(
    RTRuntimeRef Runtime
);

Void RTCharacterApplyForceEffect(
	RTRuntimeRef Runtime,
	RTCharacterRef Character,
	RTEntityID Source,
	Int ForceEffectIndex,
	Int64 ForceValue,
	Int ForceValueType
);

Void RTCharacterCancelForceEffect(
	RTRuntimeRef Runtime,
	RTCharacterRef Character,
	RTEntityID Source,
	Int ForceEffectIndex,
	Int64 ForceValue,
	Int ForceValueType
);

Void RTMobApplyForceEffect(
	RTRuntimeRef Runtime,
	RTMobRef Mob,
	RTEntityID Source,
	Int ForceEffectIndex,
	Int64 ForceValue,
	Int ForceValueType
);

Void RTMobCancelForceEffect(
	RTRuntimeRef Runtime,
	RTMobRef Mob,
	RTEntityID Source,
	Int ForceEffectIndex,
	Int64 ForceValue,
	Int ForceValueType
);

EXTERN_C_END
