DROP DATABASE IF EXISTS `auth`;

CREATE DATABASE `auth`;

USE `auth`;

DROP TABLE IF EXISTS `accounts`;

CREATE TABLE `accounts` (
    `id` INT NOT NULL AUTO_INCREMENT,

    `username` VARCHAR(16) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `email_verified` BOOLEAN NOT NULL DEFAULT FALSE,
    `salt` BINARY(64) NOT NULL,
    `hash` BINARY(64) NOT NULL,

    `created_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    `updated_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    `deleted_at` BIGINT UNSIGNED DEFAULT NULL,

    PRIMARY KEY (`id`),
    UNIQUE (`username`),
    UNIQUE (`email`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `sessions`;

CREATE TABLE `sessions` (
    `account_id` INT NOT NULL,
    
    `online` BOOLEAN NOT NULL DEFAULT FALSE,
    `session_key` VARCHAR(32) NOT NULL DEFAULT '',
    `session_ip` VARCHAR(15) NOT NULL DEFAULT '127.0.0.1',
    `session_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    
    `created_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),
    `updated_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(),

    PRIMARY KEY (`account_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `blacklists`;

CREATE TABLE `blacklists` (
    `id` INT NOT NULL AUTO_INCREMENT,

    `account_id` INT,
    `address_ip` VARCHAR(16),
    `description` VARCHAR(255) NOT NULL,

    `created_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(CURRENT_TIMESTAMP),
    `updated_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(CURRENT_TIMESTAMP),

    PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `characters`;

CREATE TABLE `characters` (
    `account_id` INT NOT NULL,

    `server_id` TINYINT UNSIGNED NOT NULL,
    `character_count` TINYINT UNSIGNED NOT NULL,
    
    `created_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(CURRENT_TIMESTAMP),
    `updated_at` BIGINT UNSIGNED NOT NULL DEFAULT UNIX_TIMESTAMP(CURRENT_TIMESTAMP),

    PRIMARY KEY (`account_id`, `server_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;
